# Markdownlint configuration for go-unifi
# Relaxed rules for technical documentation

# MD029: Ordered list prefix - allow any style (1/1/1 or 1/2/3)
MD029:
  style: "ordered"

# MD013: Line length - disabled for long code examples and URLs
MD013: false

MD041: false
