// Package unifi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package unifi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for HostType.
const (
	Console       HostType = "console"
	NetworkServer HostType = "network-server"
)

// Defines values for ISPMetricsQueryInterval.
const (
	N1h ISPMetricsQueryInterval = "1h"
	N5m ISPMetricsQueryInterval = "5m"
)

// Defines values for ISPMetricsQueryResponseDataStatus.
const (
	PartialSuccess ISPMetricsQueryResponseDataStatus = "partialSuccess"
	Success        ISPMetricsQueryResponseDataStatus = "success"
)

// Device defines model for Device.
type Device struct {
	// Id Unique device identifier
	Id *string `json:"id,omitempty"`

	// Uidb Device database information (structure varies by UniFi OS version)
	Uidb *map[string]interface{} `json:"uidb,omitempty"`
}

// DevicesResponse defines model for DevicesResponse.
type DevicesResponse struct {
	Data []Device `json:"data"`

	// HttpStatusCode HTTP status code
	HttpStatusCode int `json:"httpStatusCode"`

	// TraceId Unique identifier for debugging purposes
	TraceId string `json:"traceId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// HttpStatusCode HTTP status code
	HttpStatusCode int `json:"httpStatusCode"`

	// Message Human-readable error message
	Message string `json:"message"`

	// TraceId Unique identifier for debugging purposes
	TraceId string `json:"traceId"`
}

// Host defines model for Host.
type Host struct {
	// HardwareId Hardware identifier of the device
	HardwareId string `json:"hardwareId"`

	// Id Unique identifier of the host device
	Id string `json:"id"`

	// IpAddress Current IP address of the device
	IpAddress *string `json:"ipAddress,omitempty"`

	// IsBlocked Indicates if the device is blocked from cloud access
	IsBlocked *bool `json:"isBlocked,omitempty"`

	// LastConnectionStateChange Time in RFC3339 format when the connection state last changed
	LastConnectionStateChange *time.Time `json:"lastConnectionStateChange,omitempty"`

	// LatestBackupTime Time in RFC3339 format of the latest device backup
	LatestBackupTime *time.Time `json:"latestBackupTime,omitempty"`

	// Owner Indicates if the current user is the owner of this device
	Owner *bool `json:"owner,omitempty"`

	// RegistrationTime Time in RFC3339 format when the device was registered to the cloud
	RegistrationTime *time.Time `json:"registrationTime,omitempty"`

	// ReportedState Device's reported state information
	ReportedState *Host_ReportedState `json:"reportedState,omitempty"`

	// Type Type of the device (console, network-server)
	Type HostType `json:"type"`

	// UserData User-specific data associated with the device including permissions and role information
	UserData *Host_UserData `json:"userData,omitempty"`
}

// Host_ReportedState_Wans_Item defines model for Host.ReportedState.Wans.Item.
type Host_ReportedState_Wans_Item struct {
	AssociatedInterface  *string                `json:"associatedInterface,omitempty"`
	Enabled              *bool                  `json:"enabled,omitempty"`
	Interface            *string                `json:"interface,omitempty"`
	Ipv4                 *string                `json:"ipv4,omitempty"`
	Mac                  *string                `json:"mac,omitempty"`
	Plugged              *bool                  `json:"plugged,omitempty"`
	Port                 *int                   `json:"port,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Host_ReportedState Device's reported state information
type Host_ReportedState struct {
	// Anonid Anonymous device identifier
	Anonid *openapi_types.UUID `json:"anonid,omitempty"`

	// Apps Installed applications with their status and features
	Apps *[]map[string]interface{} `json:"apps,omitempty"`

	// AutoUpdate Auto-update configuration
	AutoUpdate *map[string]interface{} `json:"autoUpdate,omitempty"`

	// AvailableChannels Available release channels
	AvailableChannels *[]string `json:"availableChannels,omitempty"`

	// ConsolesOnSameLocalNetwork Other consoles on the same local network
	ConsolesOnSameLocalNetwork *[]map[string]interface{} `json:"consolesOnSameLocalNetwork,omitempty"`

	// ControllerUuid Controller UUID
	ControllerUuid *string `json:"controller_uuid,omitempty"`

	// Controllers Installed controllers with their configuration and status
	Controllers *[]map[string]interface{} `json:"controllers,omitempty"`

	// Country Country code
	Country *int `json:"country,omitempty"`

	// DeviceErrorCode Device error code if any
	DeviceErrorCode *string `json:"deviceErrorCode"`

	// DeviceState Current device state
	DeviceState *string `json:"deviceState,omitempty"`

	// DeviceStateLastChanged Unix timestamp when device state last changed
	DeviceStateLastChanged *int `json:"deviceStateLastChanged,omitempty"`

	// DirectConnectDomain Direct connect domain for remote access
	DirectConnectDomain *string `json:"directConnectDomain,omitempty"`

	// Features Device features and capabilities
	Features *map[string]interface{} `json:"features,omitempty"`

	// FirmwareUpdate Firmware update information
	FirmwareUpdate *map[string]interface{} `json:"firmwareUpdate,omitempty"`

	// Hardware Hardware information including CPU, MAC, serial number, etc.
	Hardware *map[string]interface{} `json:"hardware,omitempty"`

	// HostType Host type identifier
	HostType *int `json:"host_type,omitempty"`

	// Hostname Device hostname
	Hostname *string `json:"hostname,omitempty"`

	// InternetIssues5min Internet connectivity issues in 5-minute periods
	InternetIssues5min *map[string]interface{} `json:"internetIssues5min,omitempty"`

	// Ip Public IP address
	Ip *string `json:"ip,omitempty"`

	// IpAddrs List of all IP addresses assigned to the device
	IpAddrs *[]string `json:"ipAddrs,omitempty"`

	// IsStacked Indicates if device is part of a stack
	IsStacked *bool `json:"isStacked,omitempty"`

	// Location Physical location of the device
	Location *struct {
		// Lat Latitude
		Lat *float32 `json:"lat,omitempty"`

		// Long Longitude
		Long *float32 `json:"long,omitempty"`

		// Radius Location radius in meters
		Radius *float32 `json:"radius,omitempty"`

		// Text Location description
		Text *string `json:"text,omitempty"`
	} `json:"location,omitempty"`

	// Mac MAC address
	Mac *string `json:"mac,omitempty"`

	// MgmtPort Management port number
	MgmtPort *int `json:"mgmt_port,omitempty"`

	// Name Device name
	Name *string `json:"name,omitempty"`

	// ReleaseChannel Current release channel
	ReleaseChannel *string `json:"releaseChannel,omitempty"`

	// State Connection state
	State *string `json:"state,omitempty"`

	// Timezone Device timezone
	Timezone *string `json:"timezone,omitempty"`

	// Uidb Device database information including images
	Uidb *map[string]interface{} `json:"uidb,omitempty"`

	// UnadoptedUnifiOSDevices List of unadopted UniFi OS devices
	UnadoptedUnifiOSDevices *[]map[string]interface{} `json:"unadoptedUnifiOSDevices,omitempty"`

	// Version UniFi OS version
	Version *string `json:"version,omitempty"`

	// Wans WAN interfaces configuration
	Wans                 *[]Host_ReportedState_Wans_Item `json:"wans,omitempty"`
	AdditionalProperties map[string]interface{}          `json:"-"`
}

// HostType Type of the device (console, network-server)
type HostType string

// Host_UserData User-specific data associated with the device including permissions and role information
type Host_UserData struct {
	// Apps List of installed applications
	Apps *[]string `json:"apps,omitempty"`

	// ConsoleGroupMembers Console group members information
	ConsoleGroupMembers *[]map[string]interface{} `json:"consoleGroupMembers,omitempty"`

	// Controllers List of available controllers
	Controllers *[]string `json:"controllers,omitempty"`

	// Email User email address
	Email *openapi_types.Email `json:"email,omitempty"`

	// Features Available features for the user
	Features *map[string]interface{} `json:"features,omitempty"`

	// FullName User's full name
	FullName *string `json:"fullName,omitempty"`

	// LocalId Local user identifier
	LocalId *openapi_types.UUID `json:"localId,omitempty"`

	// Permissions User permissions per application
	Permissions *map[string][]string `json:"permissions,omitempty"`

	// Role User role
	Role *string `json:"role,omitempty"`

	// RoleId Role identifier
	RoleId *openapi_types.UUID `json:"roleId,omitempty"`

	// Status User status
	Status               *string                `json:"status,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HostResponse defines model for HostResponse.
type HostResponse struct {
	Data Host `json:"data"`

	// HttpStatusCode HTTP status code
	HttpStatusCode int `json:"httpStatusCode"`

	// TraceId Unique identifier for debugging purposes
	TraceId string `json:"traceId"`
}

// HostsResponse defines model for HostsResponse.
type HostsResponse struct {
	Data []Host `json:"data"`

	// HttpStatusCode HTTP status code
	HttpStatusCode int `json:"httpStatusCode"`

	// NextToken Pagination token for fetching the next set of results
	NextToken *string `json:"nextToken,omitempty"`

	// TraceId Unique identifier for debugging purposes
	TraceId string `json:"traceId"`
}

// ISPMetric defines model for ISPMetric.
type ISPMetric struct {
	// Timestamp Metric timestamp
	Timestamp *time.Time `json:"timestamp,omitempty"`

	// Type Metric type
	Type *string `json:"type,omitempty"`

	// Value Metric value
	Value                *float32               `json:"value,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ISPMetricsQuery defines model for ISPMetricsQuery.
type ISPMetricsQuery struct {
	// EndTime Query end time
	EndTime *time.Time `json:"endTime,omitempty"`

	// Interval Metric interval (5-minute or 1-hour)
	Interval *ISPMetricsQueryInterval `json:"interval,omitempty"`

	// Sites List of site IDs to query
	Sites *[]string `json:"sites,omitempty"`

	// StartTime Query start time
	StartTime *time.Time `json:"startTime,omitempty"`
}

// ISPMetricsQueryInterval Metric interval (5-minute or 1-hour)
type ISPMetricsQueryInterval string

// ISPMetricsQueryResponse defines model for ISPMetricsQueryResponse.
type ISPMetricsQueryResponse struct {
	Data struct {
		Metrics *[]ISPMetric `json:"metrics,omitempty"`

		// Status Query status (partialSuccess if some sites are inaccessible)
		Status *ISPMetricsQueryResponseDataStatus `json:"status,omitempty"`
	} `json:"data"`

	// HttpStatusCode HTTP status code
	HttpStatusCode int `json:"httpStatusCode"`

	// TraceId Unique identifier for debugging purposes
	TraceId string `json:"traceId"`
}

// ISPMetricsQueryResponseDataStatus Query status (partialSuccess if some sites are inaccessible)
type ISPMetricsQueryResponseDataStatus string

// ISPMetricsResponse defines model for ISPMetricsResponse.
type ISPMetricsResponse struct {
	Data []ISPMetric `json:"data"`

	// HttpStatusCode HTTP status code
	HttpStatusCode int `json:"httpStatusCode"`

	// TraceId Unique identifier for debugging purposes
	TraceId string `json:"traceId"`
}

// SDWANConfig defines model for SDWANConfig.
type SDWANConfig struct {
	// Config SD-WAN configuration data
	Config *map[string]interface{} `json:"config,omitempty"`

	// Id Unique SD-WAN configuration identifier
	Id *string `json:"id,omitempty"`

	// Name Configuration name
	Name *string `json:"name,omitempty"`
}

// SDWANConfigResponse defines model for SDWANConfigResponse.
type SDWANConfigResponse struct {
	Data SDWANConfig `json:"data"`

	// HttpStatusCode HTTP status code
	HttpStatusCode int `json:"httpStatusCode"`

	// TraceId Unique identifier for debugging purposes
	TraceId string `json:"traceId"`
}

// SDWANConfigStatus defines model for SDWANConfigStatus.
type SDWANConfigStatus struct {
	// DeploymentProgress Deployment progress percentage
	DeploymentProgress *float32 `json:"deploymentProgress,omitempty"`

	// Errors List of deployment errors
	Errors *[]string `json:"errors,omitempty"`

	// Hubs Associated hub statuses
	Hubs *[]SDWANConfigStatus_Hubs_Item `json:"hubs,omitempty"`

	// Id SD-WAN configuration identifier
	Id *string `json:"id,omitempty"`
}

// SDWANConfigStatus_Hubs_Item defines model for SDWANConfigStatus.hubs.Item.
type SDWANConfigStatus_Hubs_Item struct {
	Id                   *string                `json:"id,omitempty"`
	Status               *string                `json:"status,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SDWANConfigStatusResponse defines model for SDWANConfigStatusResponse.
type SDWANConfigStatusResponse struct {
	Data SDWANConfigStatus `json:"data"`

	// HttpStatusCode HTTP status code
	HttpStatusCode int `json:"httpStatusCode"`

	// TraceId Unique identifier for debugging purposes
	TraceId string `json:"traceId"`
}

// SDWANConfigsResponse defines model for SDWANConfigsResponse.
type SDWANConfigsResponse struct {
	Data []SDWANConfig `json:"data"`

	// HttpStatusCode HTTP status code
	HttpStatusCode int `json:"httpStatusCode"`

	// TraceId Unique identifier for debugging purposes
	TraceId string `json:"traceId"`
}

// Site defines model for Site.
type Site struct {
	// Id Unique site identifier
	Id *string `json:"id,omitempty"`

	// Meta Site metadata (structure varies by UniFi Network version)
	Meta *map[string]interface{} `json:"meta,omitempty"`

	// Name Site name
	Name *string `json:"name,omitempty"`

	// Statistics Site statistics (structure varies by UniFi Network version)
	Statistics *map[string]interface{} `json:"statistics,omitempty"`
}

// SitesResponse defines model for SitesResponse.
type SitesResponse struct {
	Data []Site `json:"data"`

	// HttpStatusCode HTTP status code
	HttpStatusCode int `json:"httpStatusCode"`

	// TraceId Unique identifier for debugging purposes
	TraceId string `json:"traceId"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	// Data The actual response payload
	Data map[string]interface{} `json:"data"`

	// HttpStatusCode HTTP status code
	HttpStatusCode int `json:"httpStatusCode"`

	// TraceId Unique identifier for debugging purposes
	TraceId string `json:"traceId"`
}

// BadGateway defines model for BadGateway.
type BadGateway = ErrorResponse

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// RateLimited defines model for RateLimited.
type RateLimited = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListHostsParams defines parameters for ListHosts.
type ListHostsParams struct {
	// PageSize Number of items to return per page
	PageSize *string `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// NextToken Token for pagination to retrieve the next set of results
	NextToken *string `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// QueryISPMetricsJSONRequestBody defines body for QueryISPMetrics for application/json ContentType.
type QueryISPMetricsJSONRequestBody = ISPMetricsQuery

// Getter for additional properties for Host_ReportedState_Wans_Item. Returns the specified
// element and whether it was found
func (a Host_ReportedState_Wans_Item) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Host_ReportedState_Wans_Item
func (a *Host_ReportedState_Wans_Item) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Host_ReportedState_Wans_Item to handle AdditionalProperties
func (a *Host_ReportedState_Wans_Item) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["associatedInterface"]; found {
		err = json.Unmarshal(raw, &a.AssociatedInterface)
		if err != nil {
			return fmt.Errorf("error reading 'associatedInterface': %w", err)
		}
		delete(object, "associatedInterface")
	}

	if raw, found := object["enabled"]; found {
		err = json.Unmarshal(raw, &a.Enabled)
		if err != nil {
			return fmt.Errorf("error reading 'enabled': %w", err)
		}
		delete(object, "enabled")
	}

	if raw, found := object["interface"]; found {
		err = json.Unmarshal(raw, &a.Interface)
		if err != nil {
			return fmt.Errorf("error reading 'interface': %w", err)
		}
		delete(object, "interface")
	}

	if raw, found := object["ipv4"]; found {
		err = json.Unmarshal(raw, &a.Ipv4)
		if err != nil {
			return fmt.Errorf("error reading 'ipv4': %w", err)
		}
		delete(object, "ipv4")
	}

	if raw, found := object["mac"]; found {
		err = json.Unmarshal(raw, &a.Mac)
		if err != nil {
			return fmt.Errorf("error reading 'mac': %w", err)
		}
		delete(object, "mac")
	}

	if raw, found := object["plugged"]; found {
		err = json.Unmarshal(raw, &a.Plugged)
		if err != nil {
			return fmt.Errorf("error reading 'plugged': %w", err)
		}
		delete(object, "plugged")
	}

	if raw, found := object["port"]; found {
		err = json.Unmarshal(raw, &a.Port)
		if err != nil {
			return fmt.Errorf("error reading 'port': %w", err)
		}
		delete(object, "port")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Host_ReportedState_Wans_Item to handle AdditionalProperties
func (a Host_ReportedState_Wans_Item) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AssociatedInterface != nil {
		object["associatedInterface"], err = json.Marshal(a.AssociatedInterface)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'associatedInterface': %w", err)
		}
	}

	if a.Enabled != nil {
		object["enabled"], err = json.Marshal(a.Enabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'enabled': %w", err)
		}
	}

	if a.Interface != nil {
		object["interface"], err = json.Marshal(a.Interface)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'interface': %w", err)
		}
	}

	if a.Ipv4 != nil {
		object["ipv4"], err = json.Marshal(a.Ipv4)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ipv4': %w", err)
		}
	}

	if a.Mac != nil {
		object["mac"], err = json.Marshal(a.Mac)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mac': %w", err)
		}
	}

	if a.Plugged != nil {
		object["plugged"], err = json.Marshal(a.Plugged)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'plugged': %w", err)
		}
	}

	if a.Port != nil {
		object["port"], err = json.Marshal(a.Port)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'port': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Host_ReportedState. Returns the specified
// element and whether it was found
func (a Host_ReportedState) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Host_ReportedState
func (a *Host_ReportedState) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Host_ReportedState to handle AdditionalProperties
func (a *Host_ReportedState) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["anonid"]; found {
		err = json.Unmarshal(raw, &a.Anonid)
		if err != nil {
			return fmt.Errorf("error reading 'anonid': %w", err)
		}
		delete(object, "anonid")
	}

	if raw, found := object["apps"]; found {
		err = json.Unmarshal(raw, &a.Apps)
		if err != nil {
			return fmt.Errorf("error reading 'apps': %w", err)
		}
		delete(object, "apps")
	}

	if raw, found := object["autoUpdate"]; found {
		err = json.Unmarshal(raw, &a.AutoUpdate)
		if err != nil {
			return fmt.Errorf("error reading 'autoUpdate': %w", err)
		}
		delete(object, "autoUpdate")
	}

	if raw, found := object["availableChannels"]; found {
		err = json.Unmarshal(raw, &a.AvailableChannels)
		if err != nil {
			return fmt.Errorf("error reading 'availableChannels': %w", err)
		}
		delete(object, "availableChannels")
	}

	if raw, found := object["consolesOnSameLocalNetwork"]; found {
		err = json.Unmarshal(raw, &a.ConsolesOnSameLocalNetwork)
		if err != nil {
			return fmt.Errorf("error reading 'consolesOnSameLocalNetwork': %w", err)
		}
		delete(object, "consolesOnSameLocalNetwork")
	}

	if raw, found := object["controller_uuid"]; found {
		err = json.Unmarshal(raw, &a.ControllerUuid)
		if err != nil {
			return fmt.Errorf("error reading 'controller_uuid': %w", err)
		}
		delete(object, "controller_uuid")
	}

	if raw, found := object["controllers"]; found {
		err = json.Unmarshal(raw, &a.Controllers)
		if err != nil {
			return fmt.Errorf("error reading 'controllers': %w", err)
		}
		delete(object, "controllers")
	}

	if raw, found := object["country"]; found {
		err = json.Unmarshal(raw, &a.Country)
		if err != nil {
			return fmt.Errorf("error reading 'country': %w", err)
		}
		delete(object, "country")
	}

	if raw, found := object["deviceErrorCode"]; found {
		err = json.Unmarshal(raw, &a.DeviceErrorCode)
		if err != nil {
			return fmt.Errorf("error reading 'deviceErrorCode': %w", err)
		}
		delete(object, "deviceErrorCode")
	}

	if raw, found := object["deviceState"]; found {
		err = json.Unmarshal(raw, &a.DeviceState)
		if err != nil {
			return fmt.Errorf("error reading 'deviceState': %w", err)
		}
		delete(object, "deviceState")
	}

	if raw, found := object["deviceStateLastChanged"]; found {
		err = json.Unmarshal(raw, &a.DeviceStateLastChanged)
		if err != nil {
			return fmt.Errorf("error reading 'deviceStateLastChanged': %w", err)
		}
		delete(object, "deviceStateLastChanged")
	}

	if raw, found := object["directConnectDomain"]; found {
		err = json.Unmarshal(raw, &a.DirectConnectDomain)
		if err != nil {
			return fmt.Errorf("error reading 'directConnectDomain': %w", err)
		}
		delete(object, "directConnectDomain")
	}

	if raw, found := object["features"]; found {
		err = json.Unmarshal(raw, &a.Features)
		if err != nil {
			return fmt.Errorf("error reading 'features': %w", err)
		}
		delete(object, "features")
	}

	if raw, found := object["firmwareUpdate"]; found {
		err = json.Unmarshal(raw, &a.FirmwareUpdate)
		if err != nil {
			return fmt.Errorf("error reading 'firmwareUpdate': %w", err)
		}
		delete(object, "firmwareUpdate")
	}

	if raw, found := object["hardware"]; found {
		err = json.Unmarshal(raw, &a.Hardware)
		if err != nil {
			return fmt.Errorf("error reading 'hardware': %w", err)
		}
		delete(object, "hardware")
	}

	if raw, found := object["host_type"]; found {
		err = json.Unmarshal(raw, &a.HostType)
		if err != nil {
			return fmt.Errorf("error reading 'host_type': %w", err)
		}
		delete(object, "host_type")
	}

	if raw, found := object["hostname"]; found {
		err = json.Unmarshal(raw, &a.Hostname)
		if err != nil {
			return fmt.Errorf("error reading 'hostname': %w", err)
		}
		delete(object, "hostname")
	}

	if raw, found := object["internetIssues5min"]; found {
		err = json.Unmarshal(raw, &a.InternetIssues5min)
		if err != nil {
			return fmt.Errorf("error reading 'internetIssues5min': %w", err)
		}
		delete(object, "internetIssues5min")
	}

	if raw, found := object["ip"]; found {
		err = json.Unmarshal(raw, &a.Ip)
		if err != nil {
			return fmt.Errorf("error reading 'ip': %w", err)
		}
		delete(object, "ip")
	}

	if raw, found := object["ipAddrs"]; found {
		err = json.Unmarshal(raw, &a.IpAddrs)
		if err != nil {
			return fmt.Errorf("error reading 'ipAddrs': %w", err)
		}
		delete(object, "ipAddrs")
	}

	if raw, found := object["isStacked"]; found {
		err = json.Unmarshal(raw, &a.IsStacked)
		if err != nil {
			return fmt.Errorf("error reading 'isStacked': %w", err)
		}
		delete(object, "isStacked")
	}

	if raw, found := object["location"]; found {
		err = json.Unmarshal(raw, &a.Location)
		if err != nil {
			return fmt.Errorf("error reading 'location': %w", err)
		}
		delete(object, "location")
	}

	if raw, found := object["mac"]; found {
		err = json.Unmarshal(raw, &a.Mac)
		if err != nil {
			return fmt.Errorf("error reading 'mac': %w", err)
		}
		delete(object, "mac")
	}

	if raw, found := object["mgmt_port"]; found {
		err = json.Unmarshal(raw, &a.MgmtPort)
		if err != nil {
			return fmt.Errorf("error reading 'mgmt_port': %w", err)
		}
		delete(object, "mgmt_port")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["releaseChannel"]; found {
		err = json.Unmarshal(raw, &a.ReleaseChannel)
		if err != nil {
			return fmt.Errorf("error reading 'releaseChannel': %w", err)
		}
		delete(object, "releaseChannel")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if raw, found := object["timezone"]; found {
		err = json.Unmarshal(raw, &a.Timezone)
		if err != nil {
			return fmt.Errorf("error reading 'timezone': %w", err)
		}
		delete(object, "timezone")
	}

	if raw, found := object["uidb"]; found {
		err = json.Unmarshal(raw, &a.Uidb)
		if err != nil {
			return fmt.Errorf("error reading 'uidb': %w", err)
		}
		delete(object, "uidb")
	}

	if raw, found := object["unadoptedUnifiOSDevices"]; found {
		err = json.Unmarshal(raw, &a.UnadoptedUnifiOSDevices)
		if err != nil {
			return fmt.Errorf("error reading 'unadoptedUnifiOSDevices': %w", err)
		}
		delete(object, "unadoptedUnifiOSDevices")
	}

	if raw, found := object["version"]; found {
		err = json.Unmarshal(raw, &a.Version)
		if err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
		delete(object, "version")
	}

	if raw, found := object["wans"]; found {
		err = json.Unmarshal(raw, &a.Wans)
		if err != nil {
			return fmt.Errorf("error reading 'wans': %w", err)
		}
		delete(object, "wans")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Host_ReportedState to handle AdditionalProperties
func (a Host_ReportedState) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Anonid != nil {
		object["anonid"], err = json.Marshal(a.Anonid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'anonid': %w", err)
		}
	}

	if a.Apps != nil {
		object["apps"], err = json.Marshal(a.Apps)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'apps': %w", err)
		}
	}

	if a.AutoUpdate != nil {
		object["autoUpdate"], err = json.Marshal(a.AutoUpdate)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'autoUpdate': %w", err)
		}
	}

	if a.AvailableChannels != nil {
		object["availableChannels"], err = json.Marshal(a.AvailableChannels)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'availableChannels': %w", err)
		}
	}

	if a.ConsolesOnSameLocalNetwork != nil {
		object["consolesOnSameLocalNetwork"], err = json.Marshal(a.ConsolesOnSameLocalNetwork)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'consolesOnSameLocalNetwork': %w", err)
		}
	}

	if a.ControllerUuid != nil {
		object["controller_uuid"], err = json.Marshal(a.ControllerUuid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'controller_uuid': %w", err)
		}
	}

	if a.Controllers != nil {
		object["controllers"], err = json.Marshal(a.Controllers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'controllers': %w", err)
		}
	}

	if a.Country != nil {
		object["country"], err = json.Marshal(a.Country)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'country': %w", err)
		}
	}

	if a.DeviceErrorCode != nil {
		object["deviceErrorCode"], err = json.Marshal(a.DeviceErrorCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceErrorCode': %w", err)
		}
	}

	if a.DeviceState != nil {
		object["deviceState"], err = json.Marshal(a.DeviceState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceState': %w", err)
		}
	}

	if a.DeviceStateLastChanged != nil {
		object["deviceStateLastChanged"], err = json.Marshal(a.DeviceStateLastChanged)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceStateLastChanged': %w", err)
		}
	}

	if a.DirectConnectDomain != nil {
		object["directConnectDomain"], err = json.Marshal(a.DirectConnectDomain)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'directConnectDomain': %w", err)
		}
	}

	if a.Features != nil {
		object["features"], err = json.Marshal(a.Features)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'features': %w", err)
		}
	}

	if a.FirmwareUpdate != nil {
		object["firmwareUpdate"], err = json.Marshal(a.FirmwareUpdate)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'firmwareUpdate': %w", err)
		}
	}

	if a.Hardware != nil {
		object["hardware"], err = json.Marshal(a.Hardware)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hardware': %w", err)
		}
	}

	if a.HostType != nil {
		object["host_type"], err = json.Marshal(a.HostType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'host_type': %w", err)
		}
	}

	if a.Hostname != nil {
		object["hostname"], err = json.Marshal(a.Hostname)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hostname': %w", err)
		}
	}

	if a.InternetIssues5min != nil {
		object["internetIssues5min"], err = json.Marshal(a.InternetIssues5min)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'internetIssues5min': %w", err)
		}
	}

	if a.Ip != nil {
		object["ip"], err = json.Marshal(a.Ip)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ip': %w", err)
		}
	}

	if a.IpAddrs != nil {
		object["ipAddrs"], err = json.Marshal(a.IpAddrs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ipAddrs': %w", err)
		}
	}

	if a.IsStacked != nil {
		object["isStacked"], err = json.Marshal(a.IsStacked)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isStacked': %w", err)
		}
	}

	if a.Location != nil {
		object["location"], err = json.Marshal(a.Location)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'location': %w", err)
		}
	}

	if a.Mac != nil {
		object["mac"], err = json.Marshal(a.Mac)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mac': %w", err)
		}
	}

	if a.MgmtPort != nil {
		object["mgmt_port"], err = json.Marshal(a.MgmtPort)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mgmt_port': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.ReleaseChannel != nil {
		object["releaseChannel"], err = json.Marshal(a.ReleaseChannel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'releaseChannel': %w", err)
		}
	}

	if a.State != nil {
		object["state"], err = json.Marshal(a.State)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'state': %w", err)
		}
	}

	if a.Timezone != nil {
		object["timezone"], err = json.Marshal(a.Timezone)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'timezone': %w", err)
		}
	}

	if a.Uidb != nil {
		object["uidb"], err = json.Marshal(a.Uidb)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'uidb': %w", err)
		}
	}

	if a.UnadoptedUnifiOSDevices != nil {
		object["unadoptedUnifiOSDevices"], err = json.Marshal(a.UnadoptedUnifiOSDevices)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'unadoptedUnifiOSDevices': %w", err)
		}
	}

	if a.Version != nil {
		object["version"], err = json.Marshal(a.Version)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'version': %w", err)
		}
	}

	if a.Wans != nil {
		object["wans"], err = json.Marshal(a.Wans)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'wans': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Host_UserData. Returns the specified
// element and whether it was found
func (a Host_UserData) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Host_UserData
func (a *Host_UserData) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Host_UserData to handle AdditionalProperties
func (a *Host_UserData) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["apps"]; found {
		err = json.Unmarshal(raw, &a.Apps)
		if err != nil {
			return fmt.Errorf("error reading 'apps': %w", err)
		}
		delete(object, "apps")
	}

	if raw, found := object["consoleGroupMembers"]; found {
		err = json.Unmarshal(raw, &a.ConsoleGroupMembers)
		if err != nil {
			return fmt.Errorf("error reading 'consoleGroupMembers': %w", err)
		}
		delete(object, "consoleGroupMembers")
	}

	if raw, found := object["controllers"]; found {
		err = json.Unmarshal(raw, &a.Controllers)
		if err != nil {
			return fmt.Errorf("error reading 'controllers': %w", err)
		}
		delete(object, "controllers")
	}

	if raw, found := object["email"]; found {
		err = json.Unmarshal(raw, &a.Email)
		if err != nil {
			return fmt.Errorf("error reading 'email': %w", err)
		}
		delete(object, "email")
	}

	if raw, found := object["features"]; found {
		err = json.Unmarshal(raw, &a.Features)
		if err != nil {
			return fmt.Errorf("error reading 'features': %w", err)
		}
		delete(object, "features")
	}

	if raw, found := object["fullName"]; found {
		err = json.Unmarshal(raw, &a.FullName)
		if err != nil {
			return fmt.Errorf("error reading 'fullName': %w", err)
		}
		delete(object, "fullName")
	}

	if raw, found := object["localId"]; found {
		err = json.Unmarshal(raw, &a.LocalId)
		if err != nil {
			return fmt.Errorf("error reading 'localId': %w", err)
		}
		delete(object, "localId")
	}

	if raw, found := object["permissions"]; found {
		err = json.Unmarshal(raw, &a.Permissions)
		if err != nil {
			return fmt.Errorf("error reading 'permissions': %w", err)
		}
		delete(object, "permissions")
	}

	if raw, found := object["role"]; found {
		err = json.Unmarshal(raw, &a.Role)
		if err != nil {
			return fmt.Errorf("error reading 'role': %w", err)
		}
		delete(object, "role")
	}

	if raw, found := object["roleId"]; found {
		err = json.Unmarshal(raw, &a.RoleId)
		if err != nil {
			return fmt.Errorf("error reading 'roleId': %w", err)
		}
		delete(object, "roleId")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Host_UserData to handle AdditionalProperties
func (a Host_UserData) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Apps != nil {
		object["apps"], err = json.Marshal(a.Apps)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'apps': %w", err)
		}
	}

	if a.ConsoleGroupMembers != nil {
		object["consoleGroupMembers"], err = json.Marshal(a.ConsoleGroupMembers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'consoleGroupMembers': %w", err)
		}
	}

	if a.Controllers != nil {
		object["controllers"], err = json.Marshal(a.Controllers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'controllers': %w", err)
		}
	}

	if a.Email != nil {
		object["email"], err = json.Marshal(a.Email)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'email': %w", err)
		}
	}

	if a.Features != nil {
		object["features"], err = json.Marshal(a.Features)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'features': %w", err)
		}
	}

	if a.FullName != nil {
		object["fullName"], err = json.Marshal(a.FullName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fullName': %w", err)
		}
	}

	if a.LocalId != nil {
		object["localId"], err = json.Marshal(a.LocalId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'localId': %w", err)
		}
	}

	if a.Permissions != nil {
		object["permissions"], err = json.Marshal(a.Permissions)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'permissions': %w", err)
		}
	}

	if a.Role != nil {
		object["role"], err = json.Marshal(a.Role)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'role': %w", err)
		}
	}

	if a.RoleId != nil {
		object["roleId"], err = json.Marshal(a.RoleId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'roleId': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ISPMetric. Returns the specified
// element and whether it was found
func (a ISPMetric) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ISPMetric
func (a *ISPMetric) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ISPMetric to handle AdditionalProperties
func (a *ISPMetric) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["timestamp"]; found {
		err = json.Unmarshal(raw, &a.Timestamp)
		if err != nil {
			return fmt.Errorf("error reading 'timestamp': %w", err)
		}
		delete(object, "timestamp")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if raw, found := object["value"]; found {
		err = json.Unmarshal(raw, &a.Value)
		if err != nil {
			return fmt.Errorf("error reading 'value': %w", err)
		}
		delete(object, "value")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ISPMetric to handle AdditionalProperties
func (a ISPMetric) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Timestamp != nil {
		object["timestamp"], err = json.Marshal(a.Timestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'timestamp': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	if a.Value != nil {
		object["value"], err = json.Marshal(a.Value)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'value': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SDWANConfigStatus_Hubs_Item. Returns the specified
// element and whether it was found
func (a SDWANConfigStatus_Hubs_Item) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SDWANConfigStatus_Hubs_Item
func (a *SDWANConfigStatus_Hubs_Item) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SDWANConfigStatus_Hubs_Item to handle AdditionalProperties
func (a *SDWANConfigStatus_Hubs_Item) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SDWANConfigStatus_Hubs_Item to handle AdditionalProperties
func (a SDWANConfigStatus_Hubs_Item) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetISPMetrics request
	GetISPMetrics(ctx context.Context, pType string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// QueryISPMetricsWithBody request with any body
	QueryISPMetricsWithBody(ctx context.Context, pType string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	QueryISPMetrics(ctx context.Context, pType string, body QueryISPMetricsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSDWANConfigs request
	ListSDWANConfigs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSDWANConfigById request
	GetSDWANConfigById(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSDWANConfigStatus request
	GetSDWANConfigStatus(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDevices request
	ListDevices(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListHosts request
	ListHosts(ctx context.Context, params *ListHostsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostById request
	GetHostById(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSites request
	ListSites(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetISPMetrics(ctx context.Context, pType string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetISPMetricsRequest(c.Server, pType)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) QueryISPMetricsWithBody(ctx context.Context, pType string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryISPMetricsRequestWithBody(c.Server, pType, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) QueryISPMetrics(ctx context.Context, pType string, body QueryISPMetricsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryISPMetricsRequest(c.Server, pType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSDWANConfigs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSDWANConfigsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSDWANConfigById(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSDWANConfigByIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSDWANConfigStatus(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSDWANConfigStatusRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListDevices(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDevicesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListHosts(ctx context.Context, params *ListHostsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListHostsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostById(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostByIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSites(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSitesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetISPMetricsRequest generates requests for GetISPMetrics
func NewGetISPMetricsRequest(server string, pType string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "type", runtime.ParamLocationPath, pType)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ea/isp-metrics/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewQueryISPMetricsRequest calls the generic QueryISPMetrics builder with application/json body
func NewQueryISPMetricsRequest(server string, pType string, body QueryISPMetricsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewQueryISPMetricsRequestWithBody(server, pType, "application/json", bodyReader)
}

// NewQueryISPMetricsRequestWithBody generates requests for QueryISPMetrics with any type of body
func NewQueryISPMetricsRequestWithBody(server string, pType string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "type", runtime.ParamLocationPath, pType)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ea/isp-metrics/%s/query", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListSDWANConfigsRequest generates requests for ListSDWANConfigs
func NewListSDWANConfigsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ea/sd-wan-configs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSDWANConfigByIdRequest generates requests for GetSDWANConfigById
func NewGetSDWANConfigByIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ea/sd-wan-configs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSDWANConfigStatusRequest generates requests for GetSDWANConfigStatus
func NewGetSDWANConfigStatusRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ea/sd-wan-configs/%s/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDevicesRequest generates requests for ListDevices
func NewListDevicesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/devices")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListHostsRequest generates requests for ListHosts
func NewListHostsRequest(server string, params *ListHostsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/hosts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pageSize", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NextToken != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "nextToken", runtime.ParamLocationQuery, *params.NextToken); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHostByIdRequest generates requests for GetHostById
func NewGetHostByIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/hosts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSitesRequest generates requests for ListSites
func NewListSitesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/sites")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetISPMetricsWithResponse request
	GetISPMetricsWithResponse(ctx context.Context, pType string, reqEditors ...RequestEditorFn) (*GetISPMetricsResponse, error)

	// QueryISPMetricsWithBodyWithResponse request with any body
	QueryISPMetricsWithBodyWithResponse(ctx context.Context, pType string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*QueryISPMetricsResponse, error)

	QueryISPMetricsWithResponse(ctx context.Context, pType string, body QueryISPMetricsJSONRequestBody, reqEditors ...RequestEditorFn) (*QueryISPMetricsResponse, error)

	// ListSDWANConfigsWithResponse request
	ListSDWANConfigsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSDWANConfigsResponse, error)

	// GetSDWANConfigByIdWithResponse request
	GetSDWANConfigByIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetSDWANConfigByIdResponse, error)

	// GetSDWANConfigStatusWithResponse request
	GetSDWANConfigStatusWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetSDWANConfigStatusResponse, error)

	// ListDevicesWithResponse request
	ListDevicesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDevicesResponse, error)

	// ListHostsWithResponse request
	ListHostsWithResponse(ctx context.Context, params *ListHostsParams, reqEditors ...RequestEditorFn) (*ListHostsResponse, error)

	// GetHostByIdWithResponse request
	GetHostByIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetHostByIdResponse, error)

	// ListSitesWithResponse request
	ListSitesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSitesResponse, error)
}

type GetISPMetricsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ISPMetricsResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON429      *RateLimited
	JSON500      *InternalServerError
	JSON502      *BadGateway
}

// Status returns HTTPResponse.Status
func (r GetISPMetricsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetISPMetricsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type QueryISPMetricsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ISPMetricsQueryResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON429      *RateLimited
	JSON500      *InternalServerError
	JSON502      *BadGateway
}

// Status returns HTTPResponse.Status
func (r QueryISPMetricsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r QueryISPMetricsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSDWANConfigsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SDWANConfigsResponse
	JSON401      *Unauthorized
	JSON429      *RateLimited
	JSON500      *InternalServerError
	JSON502      *BadGateway
}

// Status returns HTTPResponse.Status
func (r ListSDWANConfigsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSDWANConfigsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSDWANConfigByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SDWANConfigResponse
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON429      *RateLimited
	JSON500      *InternalServerError
	JSON502      *BadGateway
}

// Status returns HTTPResponse.Status
func (r GetSDWANConfigByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSDWANConfigByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSDWANConfigStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SDWANConfigStatusResponse
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON429      *RateLimited
	JSON500      *InternalServerError
	JSON502      *BadGateway
}

// Status returns HTTPResponse.Status
func (r GetSDWANConfigStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSDWANConfigStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListDevicesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DevicesResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON429      *RateLimited
	JSON500      *InternalServerError
	JSON502      *BadGateway
}

// Status returns HTTPResponse.Status
func (r ListDevicesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDevicesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListHostsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HostsResponse
	JSON401      *Unauthorized
	JSON429      *RateLimited
	JSON500      *InternalServerError
	JSON502      *BadGateway
}

// Status returns HTTPResponse.Status
func (r ListHostsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListHostsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HostResponse
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON429      *RateLimited
	JSON500      *InternalServerError
	JSON502      *BadGateway
}

// Status returns HTTPResponse.Status
func (r GetHostByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSitesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SitesResponse
	JSON401      *Unauthorized
	JSON429      *RateLimited
	JSON500      *InternalServerError
	JSON502      *BadGateway
}

// Status returns HTTPResponse.Status
func (r ListSitesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSitesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetISPMetricsWithResponse request returning *GetISPMetricsResponse
func (c *ClientWithResponses) GetISPMetricsWithResponse(ctx context.Context, pType string, reqEditors ...RequestEditorFn) (*GetISPMetricsResponse, error) {
	rsp, err := c.GetISPMetrics(ctx, pType, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetISPMetricsResponse(rsp)
}

// QueryISPMetricsWithBodyWithResponse request with arbitrary body returning *QueryISPMetricsResponse
func (c *ClientWithResponses) QueryISPMetricsWithBodyWithResponse(ctx context.Context, pType string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*QueryISPMetricsResponse, error) {
	rsp, err := c.QueryISPMetricsWithBody(ctx, pType, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryISPMetricsResponse(rsp)
}

func (c *ClientWithResponses) QueryISPMetricsWithResponse(ctx context.Context, pType string, body QueryISPMetricsJSONRequestBody, reqEditors ...RequestEditorFn) (*QueryISPMetricsResponse, error) {
	rsp, err := c.QueryISPMetrics(ctx, pType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryISPMetricsResponse(rsp)
}

// ListSDWANConfigsWithResponse request returning *ListSDWANConfigsResponse
func (c *ClientWithResponses) ListSDWANConfigsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSDWANConfigsResponse, error) {
	rsp, err := c.ListSDWANConfigs(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSDWANConfigsResponse(rsp)
}

// GetSDWANConfigByIdWithResponse request returning *GetSDWANConfigByIdResponse
func (c *ClientWithResponses) GetSDWANConfigByIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetSDWANConfigByIdResponse, error) {
	rsp, err := c.GetSDWANConfigById(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSDWANConfigByIdResponse(rsp)
}

// GetSDWANConfigStatusWithResponse request returning *GetSDWANConfigStatusResponse
func (c *ClientWithResponses) GetSDWANConfigStatusWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetSDWANConfigStatusResponse, error) {
	rsp, err := c.GetSDWANConfigStatus(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSDWANConfigStatusResponse(rsp)
}

// ListDevicesWithResponse request returning *ListDevicesResponse
func (c *ClientWithResponses) ListDevicesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDevicesResponse, error) {
	rsp, err := c.ListDevices(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDevicesResponse(rsp)
}

// ListHostsWithResponse request returning *ListHostsResponse
func (c *ClientWithResponses) ListHostsWithResponse(ctx context.Context, params *ListHostsParams, reqEditors ...RequestEditorFn) (*ListHostsResponse, error) {
	rsp, err := c.ListHosts(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListHostsResponse(rsp)
}

// GetHostByIdWithResponse request returning *GetHostByIdResponse
func (c *ClientWithResponses) GetHostByIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetHostByIdResponse, error) {
	rsp, err := c.GetHostById(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostByIdResponse(rsp)
}

// ListSitesWithResponse request returning *ListSitesResponse
func (c *ClientWithResponses) ListSitesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSitesResponse, error) {
	rsp, err := c.ListSites(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSitesResponse(rsp)
}

// ParseGetISPMetricsResponse parses an HTTP response from a GetISPMetricsWithResponse call
func ParseGetISPMetricsResponse(rsp *http.Response) (*GetISPMetricsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetISPMetricsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ISPMetricsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest RateLimited
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseQueryISPMetricsResponse parses an HTTP response from a QueryISPMetricsWithResponse call
func ParseQueryISPMetricsResponse(rsp *http.Response) (*QueryISPMetricsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &QueryISPMetricsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ISPMetricsQueryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest RateLimited
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseListSDWANConfigsResponse parses an HTTP response from a ListSDWANConfigsWithResponse call
func ParseListSDWANConfigsResponse(rsp *http.Response) (*ListSDWANConfigsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSDWANConfigsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SDWANConfigsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest RateLimited
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetSDWANConfigByIdResponse parses an HTTP response from a GetSDWANConfigByIdWithResponse call
func ParseGetSDWANConfigByIdResponse(rsp *http.Response) (*GetSDWANConfigByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSDWANConfigByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SDWANConfigResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest RateLimited
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetSDWANConfigStatusResponse parses an HTTP response from a GetSDWANConfigStatusWithResponse call
func ParseGetSDWANConfigStatusResponse(rsp *http.Response) (*GetSDWANConfigStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSDWANConfigStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SDWANConfigStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest RateLimited
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseListDevicesResponse parses an HTTP response from a ListDevicesWithResponse call
func ParseListDevicesResponse(rsp *http.Response) (*ListDevicesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDevicesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DevicesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest RateLimited
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseListHostsResponse parses an HTTP response from a ListHostsWithResponse call
func ParseListHostsResponse(rsp *http.Response) (*ListHostsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListHostsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HostsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest RateLimited
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetHostByIdResponse parses an HTTP response from a GetHostByIdWithResponse call
func ParseGetHostByIdResponse(rsp *http.Response) (*GetHostByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest RateLimited
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseListSitesResponse parses an HTTP response from a ListSitesWithResponse call
func ParseListSitesResponse(rsp *http.Response) (*ListSitesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSitesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SitesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest RateLimited
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8a3Mbt3Z/BbPpTBwPKVEvx9an0pKccK4t6YpSc9vYY4O7hySiXWCDByXGw//eOQD2",
	"xQUpUrbqtHU+RVwc4OC8X/DnKBZZLjhwraLjz5EElQuuwP7xmia/UA13dI5/xYJr4Br/l+Z5ymKqmeC7",
	"fyjB8Te4p1megluZQHQcve6ffvylf332W/8/o0401TofaqqNOrGfj3r7nSgDpegEF9/kSkugGVEgZywG",
	"YjidUZbSUQpRJ9KSxjBIouOIjuK9/YNo0YlUPIWM4oH/JmEcHUc/7FaX2XVf1e6ZlEJe+WtFi8WiEyWg",
	"YslyRB/RpAmZuGuSLjHLeADC43GvaXIFfxpQ+tHUuDr7583Z8DpAjcNer06NAZ/RlCVEugNJTiXNQINU",
	"T0+L4swuyWg6FjKD6jc155re44EDrkFymg5BzkDajR9FlsH59dnVef/tx7Orq4uroJwsUcada/kD0rPn",
	"SYkSPnLRic6FfiMMTx518fOL649vLm7OT4PScFi/8xUoYWQMhAtNxvbEJ73weXEM6RactzLgsUgEKIsK",
	"3DOl8dwrquEty5iGx9Hiqn999vHt4N0gqBr7rxrEoBpIiocRuI8BEnhialwLQTLK5wUpFFIliMQUaIIq",
	"evw5ugIt593+WINViyX6mmwEkogxURALniiiBbmjTJMRjIUEIhGa8UnUqYh1VL+QnudIC8Y1TEAi1otO",
	"dMOp0VMh2V+PZMPNef/m+teLq8F/nYWlci9ko/qXA3IL86dlQv1upEuYP1tIkjGlGJ+UaCzKQy0jTgGt",
	"OP5fLkUOUjPn21jS5ssNZ38aIIkFISwBrtmYgTUvjuBKS2TLohMZlowsZZOEIThNL2v7a2lg+QoOE5JQ",
	"TUdUAWEcjavlCXmmtDSxNhLIjEoGiozm5IazN4xcDMkMpGKC/1ThIUZ/QKztXZd+6fhzVElNRDJNL8bR",
	"8e/rmTA0cQyqAlx0lomGuFviacjUQzz1lK9QpFLSeQjnD4tO1JSAFruchC4z7B2Np4xDVwJNMFBwppnY",
	"xTXVWRbsFjOXJX35nF+vry+Jsgtam1utWNbHmp609jIZ5csYF6vrSAf0axnvUuFWSHIlwmQsJElgZCYT",
	"VJbcyFxglFc/0CltN4Hx4dGL7mTKfn75qn3qohOhIWQSjczvkSfHEgWr+1dIfgjI6q/CRVNNZk+pTO6o",
	"DN7sV/+tfjcxJnpa6G2ITmwjEvltpkLpdXvl/SSRoFR7yxMjJXBNBpeEujUboKZepyK+hQCGA56gzQZF",
	"WH0XwhQZORgyliIjcSpMQqhV3uqIkRApUI5npFTpE8E5xLgzsglOppSHpPOaZWiZyNWbk4ODg1fEmShy",
	"NwVuUYjLbaw+AMG9SWx3Qxfo1kfHaCqgq1kWvHSKt9KvaXxrcjxxYzw8OR18QY+R3Wfjw8UdDznlFrVj",
	"z02jQCLN8TcL67BgqsXVGsklTJjS0lr3rW5YUtpf7o4q4jYDCQkGChY3ZPnGN5aQC6khsZx/jNP6EXFw",
	"e3i215xX1FlSX8oFD2lcnws+z4RRQQ9bXsUYloRuQfNchdimNE1TSEgtxlHkjukpUorJwm5TnpAxUPSx",
	"qCWlC1tHi5a9anqyTkSNFjd5sjVZ+0aLrrGAqFJjNjGyIGbr0DIPRqXlkAao0C+WEAkpYHQRF2trV237",
	"j6XrxIIrkYK64EOawVsR0/Qc9J2Qt+0jL/QU0NU6CCKc1CqaAUkRkHAP2UZgNT0xZJUiTUF+tGLQNrHl",
	"AnJzMwg682qPteJSW1aXlgY3rNA4+flqIhMLw7Wch65mPxQBRjukcFpjA6VwmOIjzCoIQlNGOYYO3KSu",
	"lNJEs6Ka27y0EGHH5vXWmoBo/SZv0ed4txDyvfcErZXSNMudzavvvexVArRgEuLCqZ2KjDIeoIddVPgs",
	"kthlNhKSkAkNLZ9Z3aS0FI8J8QtgKz4xzemIpcxCBeRjzGSGAc1jzMgbD0u8KWla5dZRRVy13SFVxFVL",
	"WBiPU5NgKHlyedMh7/onHaJAMtR7m912COh4J4iFUPqj+7UV3GHohZ+CyVeN/bgHp9lqHSgXhEIuW88B",
	"PVDKgDrKnOhsTpCBhy+DoRnTc8LsbujRj7oZ40YDyUEykQS5zvI26pdmlLK4Fj2uDj8Dlu0tUzY+omla",
	"2wKFUCk24VXsUEYtm/sFpoaabhCkVgFqTqXDBhU6vg2HpcJ56wAlpnPF0IcUS1pxdDPiSKkOEIRqpk3d",
	"ljrJdEfzSQBC8MlKEEkTZkJ0L1B0C1AAqkrt8iYa7vWaLeo/hxKvlhhlNA5kxf2TdRKUTTL9EYO5UD7N",
	"6QQyNPW4wKtyUAPXat8qzfPBiY9jVvuZpSAmtJVa4amW8pNg1swy+Evw1eiXC5687lOZUZbRSdhBGE4T",
	"kWtIbjgbs4uhr++stgAlQFVBSjzMNrGYrzoFvXejLhUi0x3lAQx/658Ta33HNAbVinw3CrCWcg2lRMyo",
	"hmRQ7Bu0aMAx+klq32qGiK0FZfnsMPjBK1/r9zw1k8mqswrFa2tU4RI3UPuHCmrVZks5J7rWhiklz3wE",
	"3yni9a7rcvwUIdFM5mo8dgmGkY01tZJOTUEUyFNfJ9xcSW4UyK7KIWZjFltdIRVry/i8dDCl2uQgbQEY",
	"cz6MtqRIH0hOg1lkoTosmE0+Jof6RQqTvwO0nypopnARmeAqkrllS3h/rXRjTTZUxgxl+lhfvs2tIaMs",
	"YNCRrcR+q3mkMtN3QF8t+q6S4DIAx1gf5QaFMhh8mzQ9D3oyxPxHRXDBSndm89xQkdJmzr5wtFWNoybO",
	"q+/+eQu+BNhRV5kcZF3SQyRCjVrBWOmMQtvNizRYu72yyrkVQXzyHT6/zMwfNJlLRWt7Vq3K7NevqlA/",
	"ZStl3S62Or6iX4Lfvn2Px2HYFjsO9/pa3EIotqcTxl30o3GF1dEx6HiK9hyVFYGJAmuZJCiT6maf4kVv",
	"f/9gv//y597+Ua/878XJq73+mzen5Q8/n/Zenr6sLTh48erN6b/6+8d7hy9+7r3cP9o73ER2kNqD4eU7",
	"0JLF20UnZYkjEGrb7aoiyMbF3LBnL7bDjwGgGU3Naij3tZWuhOKKkhDqnwZcFat5ZeBJuN5t1xPgCfE3",
	"2+y6Njab0XQl8sUC8qzMu4Uke92pMI0g5iiLOtHeNBizKKbXBdT4mQxObZv+T3vtbVyj0lTqdTSxC7ah",
	"ygaMeUrL0Pw1c6dubDIqVQrTKmjuS0Jpo8iznErNaOoxJmxMlMjAskkRV6lylT02SqEuA8oUBb/mFgGh",
	"WGzQa29Yhm9vjNdQNoz78PS3/vmJTcJCHffi980jsOFpF1O8Zg3d3iFUAlvdlA3us34eI1yPOGnsEI7j",
	"QtpUo8y3cv515jzMv2GpOEsnQZ6KeQZcX0oxCbetT8s1JPeLMDCMgWvXwc/oPctQg/bsLB7j7q9eoMBl",
	"ew9rTGmFD/FLtzGlUzMKNb+qRHFqRt5KbN7kC80FrYlDt07Pw5K+tYg/IKZOAP4Gwuol8WGR/fYGs6Fi",
	"G5pMprcbJrOxw3rTlcG21RLEgiCYLZSsGR7z3ds1E2SrLKc9YlXii9rAlPZuf0u8K+AvwzyoEBgCfHu5",
	"QiHZVKCWjj5edfJSJW8KhMba0JQUI/skp/NU0CTYc/uCAbf9Xi/UAPgbzJ75yKI1e7Z64gxlF2IjmZ4P",
	"kVmOxP2c/QPmfaOnAefipu/sHajRU7yUK5bskIuRtg1lKTJiOBuzHcN2YpHZkT3l2hA76IZwIzccHBX6",
	"Fv2r278cdP9RH+yjFg83/sr4WBRDvDS2JWNfY4vG/57C/U5Kq736KdwqYGQ4Y5Ilt4wHSj9Wq6wCui6P",
	"tFjmUsxYAsp5fpplVLPY98Ux3XFgvuxLGB9LWursznv+nv/wA+k3yPKe99O0mpX2/CKUF4OMJKdKQUJm",
	"jNp0vyQEcSQqtrWD3naqnPHJe94lsz1MH3PBuFbHZK/X6fV61UE5SOLyP1x7RmU6J313jwbUChB75H84",
	"Y+PP+7Q729t9/ol0yVDTUQodJFJiLFvtAOe82tmVqFPBJ10NMiPK5LmQ2m0D1G0TRqpDlLHiifR2Mw/v",
	"edSJUhaDtwieze8G165/pd1Ua5ClUa1zE+3t9HZ6dugtB05zFh1HBzu9nQObAemplX5Ej6m86xO53c8o",
	"jQv8MoFAj/AKl8EMFBkML4kHIjSWQinbfHZpWMr4bdVzvhmgTAnD9Y+qkIOd9/xdAe0qtyxlen6MNCtT",
	"+TK79wcd12rVViU1SYEqTfYPCWb8CqFd8r857EGPJHSuLNXR9Fo5tnPsv4CuEjyXNhbvcNCntG1yVtVh",
	"8O7SE6swAkj0Sm19taYyac5ntsb8S/P3odN8oLXf620w6L/ZCH4gkQ3M4Xt3NTaV30HxOnSIhPYvEd6t",
	"PaCyIHsPgzSeNCDQ/quHgeqvURad6GgT3ELPmSzs/kb3Kp7JWQdjsozKuZOeupKgoacTlJwIfy2k6gMC",
	"hZVw98+yyOYHpTfRRRsUjijaWMFJ2VSze9Veku2851egjeRuWqNZUNE2vrAaS1Ia36qaT6CVfYfEqftO",
	"QHdszeaLtKestX0t1bE4vxbJ/Am0xtVDF80YBbFa/I8obbPq911zv0xzXb1xC91VSfeO8q5L59UGzpOS",
	"tDawFaoGqGAHvPKkJKO3RcsEXWpM07SlhG+Z0vWcO3pCYQzm9ttI4v95sbJVsCCva/Llvq8Srd3PLNkk",
	"OEtAU5ZC0hg3oiNhNKGVTwhWoUZzYierW6FQjcGv57Zt+qBFbz+vCR0ZtvG2S/v3CI5C9eCnluze4cNA",
	"5Qvk/5Wx0Vrp20Iddqvq7ANaYZ8ouDKHG05dpwid2pxR0q6Rd3wFu2MHj2ijCK0eUJ9hMbnw/1CBlirV",
	"39XoSdSomo0J6dFsbzepxkg3DlVcxcFDkswWHRLU2KlQWpG7KUjYIEpZek0nURGNHUVKMsaDMcxpOcD6",
	"ZCK6/G76ewz9FYId5HY1fFzIYsHNUhit/GwdNTup2z5KthXG58/PhYbnz4/JtXUKRSNCjMmnYob1kzXt",
	"nxrvJz+RMYM0QfGfkxmVc/QNwK2X8I/gygFpIcs+hiNt0c4I5ctILzvV9ZBbqP75CNuN8HUmI7ktaObL",
	"78j3eoV3KPJp7x5w5ZD9hatXO4VOyymVQ1t5fZKrLHV9gxGu0OWqCbRv5fKaE3rf86CQaZh6eS8Mg5P/",
	"pln4uhmPfd2/MsPB8zdNbcy6f0Dgbx+QNeZav8dgXxqDNcRqhTSXU4ZbOTnXTnlmm4zO4UnDeeHSms3y",
	"mjj89IBfDFeKLIZPmQY0+vPfbWLIJirPhDJwt39/WNSb19Yk1dvWv39Aa+Ge5YQM1mXZufTNaft+pxMZ",
	"mUbHtoOujnd3aV60sCPczmMQfKWbVU8FSzlSlaVzot+OHtzkynpYd+E2rH9I9wB0EVu24Rv9Sp6QTHCm",
	"Bdpa8qzemv2p2qxe6w1cJpR41dBbtatPxRYfFv8dAAD//4gAXeB/UQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
