tag: builtin.scopes.controllers
subjects:
  - controller:access
  - controller:network
  - controller:led
  - controller:talk
  - controller:protect
scopes:
  - access.open_door:building
  - access.open_door:door
  - access.open_door:door_group
  - access.open_door:floor
  - access.open_door:location
  - adopt:access.device
  - assign:role
  - assign:role:admin
  - assign:role:viewer
  - cloud_access:controller
  - cloud_access:system
  - delete:access.device
  - edit:access.dashboard
  - edit:access.device
  - edit:access.nfc_card
  - edit:access.face
  - edit:access.policy
  - edit:access.schedule
  - edit:access.systemlog
  - edit:backup
  - edit:cloud_access
  - edit:door_group
  - edit:feedback
  - edit:group
  - edit:holiday
  - edit:holiday_timezone
  - edit:location
  - edit:location_activity
  - edit:location_device
  - edit:location_policy
  - edit:notification
  - edit:permission
  - edit:role
  - edit:role:admin
  - edit:role:viewer
  - edit:settings
  - edit:sso
  - edit:system_info
  - edit:user
  - edit:user_credential
  - edit:user_timezone
  - edit:systemlog
  - manage:controller
  - notify:access
  - notify:led
  - notify:location
  - notify:network
  - notify:protect
  - notify:talk
  - notify:user
  - systemlog:access
  - systemlog:location
  - systemlog:system
  - systemlog:user
  - update:access.device
  - view:access.dashboard
  - view:access.device
  - view:access.face
  - view:access.nfc_card
  - view:access.policy
  - view:access.schedule
  - view:access.systemlog
  - view:backup
  - view:cloud_access
  - view:controller
  - view:door_group
  - view:group
  - view:holiday
  - view:holiday_timezone
  - view:location
  - view:location_activity
  - view:location_device
  - view:location_policy
  - view:notification
  - view:permission
  - view:role
  - view:role:admin
  - view:role:viewer
  - view:settings
  - view:sso
  - view:system_info
  - view:systemlog
  - view:user
  - view:user_timezone
