# Authorization
auth_request /internal/auth/public-api;

auth_request_set $token $sent_http_x_token;
proxy_set_header X-Token $token;

auth_request_set $setup_token $sent_http_x_setup_token;
proxy_set_header X-Setup-Token $setup_token;

auth_request_set $user_id $sent_http_x_userid;
proxy_set_header X-UserId $user_id;

auth_request_set $username $sent_http_x_username;

auth_request_set $user_role $sent_http_x_userrole;
proxy_set_header X-UserRole $user_role;

auth_request_set $user_access_mask $sent_http_x_useraccessmask;
proxy_set_header X-UserAccessMask $user_access_mask;

auth_request_set $user_permission_mask $sent_http_x_userpermissionmask;
proxy_set_header X-UserPermissionMask $user_permission_mask;

auth_request_set $expected_csrf_token $sent_http_x_expected_csrf_token;
proxy_set_header X-Expected-Csrf-Token $expected_csrf_token;

auth_request_set $provided_csrf_token $sent_http_x_provided_csrf_token;
proxy_set_header X-Provided-Csrf-Token $provided_csrf_token;

auth_request_set $apikey_id $sent_http_x_apikeyid;
proxy_set_header X-ApiKeyId $apikey_id;


# Set expected CSRF token header
# Hide the header from upstream (if provided) to avoid duplicate headers
proxy_hide_header X-Csrf-Token;
add_header X-Csrf-Token $csrf_token_header;
