location = /api/ws/consoleGroups {
    proxy_set_header X-Internal-Proxy-Client-Cert $ssl_client_escaped_cert;
    proxy_set_header X-Forwarded-For $remote_addr;

    include /usr/share/unifi-core/http/websocket.conf;

    proxy_pass http://uos_api_backend;
}