set $allow_headers 'Content-Type';
set $allow_headers '${allow_headers}, Cache-Control';
set $allow_headers '${allow_headers}, If-Modified-Since';
set $allow_headers '${allow_headers}, Jwt';
set $allow_headers '${allow_headers}, Range';
set $allow_headers '${allow_headers}, Tus-Resumable';
set $allow_headers '${allow_headers}, Upload-Length';
set $allow_headers '${allow_headers}, Upload-Metadata';
set $allow_headers '${allow_headers}, Upload-Offset';
set $allow_headers '${allow_headers}, X-Connection-Type';
set $allow_headers '${allow_headers}, X-Csrf-Token';
set $allow_headers '${allow_headers}, X-Requested-With';
set $allow_headers '${allow_headers}, X-Token-Expire-Time';
set $allow_headers '${allow_headers}, X-UidToken';
set $allow_headers '${allow_headers}, X-Updated-Csrf-Token';
set $allow_headers '${allow_headers}, X-User-Agent';
set $allow_headers '${allow_headers}, X-Api-Key';
set $allow_headers '${allow_headers}, X-Ui-Setup-Poll-Token';
set $allow_headers '${allow_headers}, Authorization';


set $expose_headers 'Content-Disposition';
set $expose_headers '${expose_headers}, Content-Range';
set $expose_headers '${expose_headers}, Filename';
set $expose_headers '${expose_headers}, Location';
set $expose_headers '${expose_headers}, Range';
set $expose_headers '${expose_headers}, Upload-Length';
set $expose_headers '${expose_headers}, Upload-Offset';
set $expose_headers '${expose_headers}, X-Connection-Type';
set $expose_headers '${expose_headers}, X-Csrf-Token';
set $expose_headers '${expose_headers}, X-File-Id';
set $expose_headers '${expose_headers}, X-Token-Expire-Time';
set $expose_headers '${expose_headers}, X-Updated-Csrf-Token';


# Handle pre-flight requests
if ($request_method = OPTIONS) {
    add_header Access-Control-Allow-Origin $cors_origin;
    add_header Access-Control-Allow-Credentials $cors_credentials;
    add_header Access-Control-Allow-Methods 'HEAD, GET, DELETE, PATCH, POST, PUT';
    add_header Access-Control-Allow-Headers $allow_headers;

    return 204;
}


# CORS headers for other requests
add_header Access-Control-Allow-Origin $cors_origin always;
add_header Access-Control-Allow-Credentials $cors_credentials always;
add_header Access-Control-Expose-Headers $expose_headers;


# Clear any duplicate headers from proxy origins
proxy_hide_header Access-Control-Allow-Origin;
proxy_hide_header Access-Control-Allow-Credentials;
proxy_hide_header Access-Control-Allow-Methods;
proxy_hide_header Access-Control-Allow-Headers;
proxy_hide_header Access-Control-Expose-Headers;
