# Forward headers to proxy target
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Internal-Proxy-Client-Cert $ssl_client_escaped_cert;

proxy_set_header X-UI-Connection-Type $connection_type;

include /usr/share/unifi-core/http/websocket.conf;

add_header Sec-Websocket-Protocol $ws_protocol always;
