# Security headers
proxy_hide_header Referrer-Policy;
add_header Referrer-Policy "no-referrer" always;

proxy_hide_header Strict-Transport-Security;
add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;

proxy_hide_header X-Content-Type-Options;
add_header X-Content-Type-Options "nosniff" always;

proxy_hide_header X-DNS-Prefetch-Control;
add_header X-DNS-Prefetch-Control "off" always;

proxy_hide_header X-Frame-Options;
add_header X-Frame-Options "SAMEORIGIN" always;

proxy_hide_header X-XSS-Protection;
add_header X-XSS-Protection "1; mode=block" always;

proxy_hide_header X-Robots-Tag;
add_header X-Robots-Tag "noindex" always;
