# Logging
access_log /data/unifi-core/logs/nginx-access.log apm;
error_log /data/unifi-core/logs/nginx-error.log;


# Static assets proxy (requires further configuration for specific site)
location @uos-proxy {
    proxy_pass http://uos_api_backend;
    proxy_pass_request_headers on;
    proxy_read_timeout 90;
}


# Model specific static assets
location /assets/ {
    include /usr/share/unifi-core/http/cors.conf;
    include /usr/share/unifi-core/http/security.conf;

    alias /usr/share/unifi-assets/;

    expires max;

    location = /assets/manifest.json {
        expires -1;
    }
}

location /idpLogin/ {
    alias /usr/lib/unifi-directory/login_portal/;
    index index.html;
}

include /data/unifi-core/config/http/shared-runnable-*.conf;
