# Site-wide configs
include /usr/share/unifi-core/http/gzip.conf;


# Internal routes
location /internal/auth/public-api {
    internal;

    proxy_pass                  http://uos_auth_backend/public-api;
    proxy_pass_request_headers  off;
    proxy_pass_request_body     off;
    proxy_set_header            Content-Length "";
    proxy_set_header            X-Original-Method $request_method;
    proxy_set_header            X-Original-URI $request_uri;
    proxy_set_header            X-Setup-Token $cookie_uos_setup_token;
    proxy_set_header            X-Token $cookie_token;
    proxy_set_header            X-Provided-Csrf-Token $http_x_csrf_token;
    proxy_set_header            X-Target-Runnable $target_runnable;
    proxy_set_header            X-Api-Key $http_x_api_key;

    proxy_cache                 auth_responses;
    proxy_cache_key             "$cookie_token|$http_x_csrf_token|$http_x_api_key|$request_method|$target_runnable|$cookie_uos_setup_token";
    proxy_cache_lock            on;
    proxy_cache_valid           200 10s;
    proxy_ignore_headers        Cache-Control Expires Set-Cookie;

}

location /internal/auth/internal-proxy {
    internal;

    proxy_pass http://uos_auth_backend/internal-proxy;
    proxy_pass_request_headers off;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";

    proxy_set_header X-Internal-Proxy-Client-Cert $ssl_client_escaped_cert;
}


# UniFi OS public API
location /api/v2/ {
    include /usr/share/unifi-core/http/cors.conf;
    include /usr/share/unifi-core/http/security.conf;
    include /usr/share/unifi-core/http/auth.conf;
    include /usr/share/unifi-core/http/proxy.conf;

    proxy_pass http://uos_agent_api_backend/api/v2/;
}

location /api/ {
    include /usr/share/unifi-core/http/cors.conf;
    include /usr/share/unifi-core/http/security.conf;
    include /usr/share/unifi-core/http/auth.conf;
    include /usr/share/unifi-core/http/proxy.conf;

    proxy_pass http://uos_api_backend/api/;
}

location /api/ping {
    include /usr/share/unifi-core/http/cors.conf;
    include /usr/share/unifi-core/http/security.conf;

    proxy_pass http://uos_api_backend/api/ping;
}


# Static assets for local portal UI
location / {
    include /usr/share/unifi-core/http/cors.conf;
    include /usr/share/unifi-core/http/security.conf;

    root /usr/share/unifi-core/app/node_modules/@ubnt/unifi-portal/dist/local;

    index index.html;
    try_files $uri $uri/ @uos-proxy /index.html;

    expires max;

    location /index.html {
        expires -1;
    }
}


# User uploaded assets
location /device-assets/ {
    include /usr/share/unifi-core/http/cors.conf;
    include /usr/share/unifi-core/http/security.conf;
    include /usr/share/unifi-core/http/auth.conf;

    alias /data/unifi-core/devices/;

    expires max;
}

