server {
    listen 443 ssl http2;
    server_name unifi.shadow;

    include /data/unifi-core/config/http/local-certs.conf;

    include /usr/share/unifi-core/http/errors.conf;

    location ~* /api/consoleGroups/(backup|firmware)$ {
        include /usr/share/unifi-core/http/proxy.conf;
        proxy_set_header            X-Group-Token $http_x_group_token;
        proxy_set_header            X-Group-Console-Id $http_x_group_console_id;
        proxy_pass http://uos_api_backend;
    }

    location = /api/ws/consoleGroups {
        include /usr/share/unifi-core/http/proxy.conf;
        proxy_set_header            X-Group-Token $http_x_group_token;
        proxy_set_header            X-Group-Console-Id $http_x_group_console_id;
        proxy_pass http://uos_api_backend;
    }
}
