server {
    access_log /data/unifi-core/logs/nginx-colocated-access.log apm;
    error_log /data/unifi-core/logs/nginx-colocated-error.log;

    listen 11083 ssl http2 default_server;
    server_name _;

    ssl_trusted_certificate /data/unifi-core/config/unifi-core-console-group-ca.crt;

    ssl_certificate /data/unifi-core/config/unifi-core-console-group-client.crt;
    ssl_certificate_key /data/unifi-core/config/unifi-core-console-group-client.key;

    include /usr/share/unifi-core/http/errors.conf;

    include /usr/share/unifi-core/http/shared-post-setup-server.conf;
    ssl_verify_client optional_no_ca;

    include /usr/share/unifi-core/http/console-group-websocket-endpoint.conf;

    location ^~ /proxy/ {
        include /usr/share/unifi-core/http/auth-internal-proxy.conf;

        location /proxy/ipc/ {

            proxy_ssl_verify on;
            include /usr/share/unifi-core/http/websocket.conf;

            proxy_pass_request_headers on;
            proxy_read_timeout 60;

            proxy_pass http://localhost:11081;
            rewrite ^/proxy/ipc(.*)$ $1 break;
            proxy_set_header Host localhost;
        }

    }
}

