server {
    listen unix:/data/unifi-core/config/http/uos-internal.sock;


    # Logging
    access_log /data/unifi-core/logs/nginx-access.log apm;
    error_log /data/unifi-core/logs/nginx-error.log;

    include /usr/share/unifi-core/http/errors.conf;

    # UOS static files
    location /device-assets/ {
        alias /data/unifi-core/devices/;
        expires max;
    }
}
