server {
    listen 443 ssl http2;

    include /data/unifi-core/config/http/direct-connect-domain.conf;
    include /data/unifi-core/config/http/direct-connect-certs.conf;

    include /usr/share/unifi-core/http/errors.conf;

    include /usr/share/unifi-core/http/shared-server-defaults.conf;
    include /usr/share/unifi-core/http/shared-post-setup-server.conf;
}

