server {
    server_name _;

    listen 80 default_server;
    listen [::]:80 default_server;
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;

    include /data/unifi-core/config/http/local-certs.conf;

    include /usr/share/unifi-core/http/errors.conf;

    include /usr/share/unifi-core/http/shared-server-defaults.conf;

    if ($host !~* ^(unifi|localhost|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+|\[[a-f0-9:]+\])$) {
        return 302 $scheme://unifi;
    }

    # UniFi OS public API
    location /api/ {
        include /usr/share/unifi-core/http/security.conf;
        include /usr/share/unifi-core/http/proxy.conf;

        proxy_pass http://uos_api_backend/api/;
    }


    # Static assets for setup UI
    location / {
        include /usr/share/unifi-core/http/security.conf;

        root /usr/share/unifi-core/app/node_modules/@ubnt/uhd-setup/dist;

        index index.html;
        try_files $uri $uri/ @uos-proxy /index.html;

        expires max;

        location /index.html {
            expires -1;
        }

    }
}

