    # Set SSL ciphers for only those approved by NIST

    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:!SHA1:!SHA256:!SHA384:!DSS:!aNULL;
    ssl_protocols TLSv1.2;
