# Websockets
if ($provided_ws_origin != $expected_ws_origin) {
    # Request violates the WS Same Origin Policy
    return 500;
}

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
proxy_cache_bypass $http_upgrade;
