name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is not working as expected?
      placeholder: Clear description of the issue
    validations:
      required: true

  - type: dropdown
    id: api-package
    attributes:
      label: API Package
      description: Which API package is affected?
      options:
        - Site Manager API (api/sitemanager)
        - Network API (api/network)
        - Internal packages
        - Other
    validations:
      required: true

  - type: input
    id: endpoint
    attributes:
      label: API Endpoint/Method
      description: Which endpoint or method is affected?
      placeholder: "Example: ListHosts, CreateDNSRecord, GetDeviceByID"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Create client with...
        2. Call method...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened, include error messages
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your test environment
      placeholder: |
        - Hardware/VM: UDR7 / UniFi Cloud Gateway / VM
        - UniFi OS version: 4.3.9
        - Network Application version: 9.4.19 (if using Network API)
        - Go version: 1.21
        - go-unifi version: v0.x.x
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Minimal code example demonstrating the issue (optional)
      placeholder: |
        ```go
        client, _ := network.New("https://unifi.local", "api-key")
        result, err := client.ListSites(ctx, nil)
        // error occurs here
        ```
      render: go

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help (optional)
