// Package network provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package network

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ClientAccessType.
const (
	BLOCKED    ClientAccessType = "BLOCKED"
	DEFAULT    ClientAccessType = "DEFAULT"
	RESTRICTED ClientAccessType = "RESTRICTED"
)

// Defines values for ClientListItemType.
const (
	WIRED    ClientListItemType = "WIRED"
	WIRELESS ClientListItemType = "WIRELESS"
)

// Defines values for DeviceState.
const (
	DeviceStateOFFLINE      DeviceState = "OFFLINE"
	DeviceStateONLINE       DeviceState = "ONLINE"
	DeviceStatePROVISIONING DeviceState = "PROVISIONING"
	DeviceStateUPGRADING    DeviceState = "UPGRADING"
)

// Defines values for DeviceListItemFeatures.
const (
	AccessPoint DeviceListItemFeatures = "accessPoint"
	Gateway     DeviceListItemFeatures = "gateway"
	Routing     DeviceListItemFeatures = "routing"
	Switching   DeviceListItemFeatures = "switching"
)

// Defines values for DeviceListItemInterfaces.
const (
	Ports  DeviceListItemInterfaces = "ports"
	Radios DeviceListItemInterfaces = "radios"
	Wan    DeviceListItemInterfaces = "wan"
)

// Defines values for DeviceListItemState.
const (
	DeviceListItemStateOFFLINE      DeviceListItemState = "OFFLINE"
	DeviceListItemStateONLINE       DeviceListItemState = "ONLINE"
	DeviceListItemStatePROVISIONING DeviceListItemState = "PROVISIONING"
	DeviceListItemStateUPGRADING    DeviceListItemState = "UPGRADING"
)

// Defines values for PoEStandard.
const (
	N8023af PoEStandard = "802.3af"
	N8023at PoEStandard = "802.3at"
	N8023bt PoEStandard = "802.3bt"
)

// Defines values for PoEState.
const (
	PoEStateDISABLED PoEState = "DISABLED"
	PoEStateDOWN     PoEState = "DOWN"
	PoEStateUP       PoEState = "UP"
)

// Defines values for PortConnector.
const (
	RJ45    PortConnector = "RJ45"
	SFP     PortConnector = "SFP"
	SFPPLUS PortConnector = "SFPPLUS"
)

// Defines values for PortState.
const (
	PortStateDOWN PortState = "DOWN"
	PortStateUP   PortState = "UP"
)

// Defines values for RadioChannelWidthMHz.
const (
	N160 RadioChannelWidthMHz = 160
	N20  RadioChannelWidthMHz = 20
	N40  RadioChannelWidthMHz = 40
	N80  RadioChannelWidthMHz = 80
)

// Defines values for RadioFrequencyGHz.
const (
	N24 RadioFrequencyGHz = 2.4
	N5  RadioFrequencyGHz = 5
	N6  RadioFrequencyGHz = 6
)

// Defines values for RadioWlanStandard.
const (
	N80211a  RadioWlanStandard = "802.11a"
	N80211ac RadioWlanStandard = "802.11ac"
	N80211ax RadioWlanStandard = "802.11ax"
	N80211b  RadioWlanStandard = "802.11b"
	N80211be RadioWlanStandard = "802.11be"
	N80211g  RadioWlanStandard = "802.11g"
	N80211n  RadioWlanStandard = "802.11n"
)

// ClientAccess defines model for ClientAccess.
type ClientAccess struct {
	// Type Access control type
	Type ClientAccessType `json:"type"`
}

// ClientAccessType Access control type
type ClientAccessType string

// ClientListItem defines model for ClientListItem.
type ClientListItem struct {
	Access ClientAccess `json:"access"`

	// ConnectedAt Timestamp when client connected (RFC3339 format)
	ConnectedAt time.Time `json:"connectedAt"`

	// Id Unique identifier for the client
	Id openapi_types.UUID `json:"id"`

	// IpAddress IP address assigned to the client
	IpAddress string `json:"ipAddress"`

	// MacAddress MAC address of the client
	MacAddress string `json:"macAddress"`

	// Name Display name or hostname of the client
	Name string `json:"name"`

	// Type Connection type
	Type ClientListItemType `json:"type"`

	// UplinkDeviceId ID of the device this client is connected to
	UplinkDeviceId openapi_types.UUID `json:"uplinkDeviceId"`
}

// ClientListItemType Connection type
type ClientListItemType string

// ClientsResponse defines model for ClientsResponse.
type ClientsResponse struct {
	// Count Number of items in current response
	Count int              `json:"count"`
	Data  []ClientListItem `json:"data"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// TotalCount Total number of items available
	TotalCount int `json:"totalCount"`
}

// Device defines model for Device.
type Device struct {
	// ConfigurationId Current configuration identifier
	ConfigurationId string `json:"configurationId"`

	// Features Feature-specific configuration and capabilities
	Features map[string]map[string]interface{} `json:"features"`

	// FirmwareUpdatable Whether firmware update is available
	FirmwareUpdatable bool `json:"firmwareUpdatable"`

	// FirmwareVersion Current firmware version
	FirmwareVersion string `json:"firmwareVersion"`

	// Id Unique identifier for the device
	Id openapi_types.UUID `json:"id"`

	// Interfaces Network interfaces available on the device
	Interfaces DeviceInterfaces `json:"interfaces"`

	// IpAddress IP address of the device
	IpAddress string `json:"ipAddress"`

	// MacAddress MAC address of the device
	MacAddress string `json:"macAddress"`

	// Model Device model identifier
	Model string `json:"model"`

	// Name Display name of the device
	Name string `json:"name"`

	// ProvisionedAt Timestamp when device was provisioned (RFC3339 format)
	ProvisionedAt time.Time `json:"provisionedAt"`

	// State Current operational state
	State DeviceState `json:"state"`

	// Supported Whether this device is officially supported
	Supported bool `json:"supported"`
}

// DeviceState Current operational state
type DeviceState string

// DeviceInterfaces Network interfaces available on the device
type DeviceInterfaces struct {
	// Ports Physical ethernet ports
	Ports *[]Port `json:"ports,omitempty"`

	// Radios Wireless radio interfaces
	Radios *[]Radio `json:"radios,omitempty"`
}

// DeviceListItem defines model for DeviceListItem.
type DeviceListItem struct {
	// Features List of features supported by this device
	Features []DeviceListItemFeatures `json:"features"`

	// Id Unique identifier for the device
	Id openapi_types.UUID `json:"id"`

	// Interfaces Types of network interfaces available
	Interfaces []DeviceListItemInterfaces `json:"interfaces"`

	// IpAddress IP address of the device
	IpAddress string `json:"ipAddress"`

	// MacAddress MAC address of the device
	MacAddress string `json:"macAddress"`

	// Model Device model identifier
	Model string `json:"model"`

	// Name Display name of the device
	Name string `json:"name"`

	// State Current operational state
	State DeviceListItemState `json:"state"`
}

// DeviceListItemFeatures defines model for DeviceListItem.Features.
type DeviceListItemFeatures string

// DeviceListItemInterfaces defines model for DeviceListItem.Interfaces.
type DeviceListItemInterfaces string

// DeviceListItemState Current operational state
type DeviceListItemState string

// DevicesResponse defines model for DevicesResponse.
type DevicesResponse struct {
	// Count Number of items in current response
	Count int              `json:"count"`
	Data  []DeviceListItem `json:"data"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// TotalCount Total number of items available
	TotalCount int `json:"totalCount"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Human-readable error message
	Message string `json:"message"`

	// RequestPath The request path that caused the error
	RequestPath string `json:"requestPath"`

	// StatusCode HTTP status code
	StatusCode int `json:"statusCode"`

	// StatusName HTTP status name
	StatusName string `json:"statusName"`

	// Timestamp Timestamp when the error occurred (RFC3339 format)
	Timestamp time.Time `json:"timestamp"`
}

// NetworkClient defines model for NetworkClient.
type NetworkClient = ClientListItem

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	// Count Number of items in current response
	Count int `json:"count"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// TotalCount Total number of items available
	TotalCount int `json:"totalCount"`
}

// PoE Power over Ethernet configuration and status
type PoE struct {
	// Enabled Whether PoE is enabled on this port
	Enabled bool `json:"enabled"`

	// Standard PoE standard supported
	Standard PoEStandard `json:"standard"`

	// State Current PoE state
	State PoEState `json:"state"`

	// Type PoE type number
	Type int `json:"type"`
}

// PoEStandard PoE standard supported
type PoEStandard string

// PoEState Current PoE state
type PoEState string

// Port defines model for Port.
type Port struct {
	// Connector Physical connector type
	Connector PortConnector `json:"connector"`

	// Idx Port index number (1-based)
	Idx int `json:"idx"`

	// MaxSpeedMbps Maximum supported speed in Mbps
	MaxSpeedMbps int `json:"maxSpeedMbps"`

	// Poe Power over Ethernet configuration and status
	Poe *PoE `json:"poe,omitempty"`

	// SpeedMbps Current negotiated speed in Mbps
	SpeedMbps int `json:"speedMbps"`

	// State Current port state
	State PortState `json:"state"`
}

// PortConnector Physical connector type
type PortConnector string

// PortState Current port state
type PortState string

// Radio defines model for Radio.
type Radio struct {
	// Channel WiFi channel number
	Channel int `json:"channel"`

	// ChannelWidthMHz Channel width in MHz
	ChannelWidthMHz RadioChannelWidthMHz `json:"channelWidthMHz"`

	// FrequencyGHz Operating frequency in GHz
	FrequencyGHz RadioFrequencyGHz `json:"frequencyGHz"`

	// WlanStandard WiFi standard supported
	WlanStandard RadioWlanStandard `json:"wlanStandard"`
}

// RadioChannelWidthMHz Channel width in MHz
type RadioChannelWidthMHz int

// RadioFrequencyGHz Operating frequency in GHz
type RadioFrequencyGHz float32

// RadioWlanStandard WiFi standard supported
type RadioWlanStandard string

// SiteListItem defines model for SiteListItem.
type SiteListItem struct {
	// Id Unique identifier for the site
	Id openapi_types.UUID `json:"id"`

	// InternalReference Internal reference name used in UniFi controller URLs
	InternalReference string `json:"internalReference"`

	// Name Display name of the site
	Name string `json:"name"`
}

// SitesResponse defines model for SitesResponse.
type SitesResponse struct {
	// Count Number of items in current response
	Count int            `json:"count"`
	Data  []SiteListItem `json:"data"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// TotalCount Total number of items available
	TotalCount int `json:"totalCount"`
}

// ClientId defines model for ClientId.
type ClientId = openapi_types.UUID

// DeviceId defines model for DeviceId.
type DeviceId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// SiteId defines model for SiteId.
type SiteId = openapi_types.UUID

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListSitesParams defines parameters for ListSites.
type ListSitesParams struct {
	// Offset Number of items to skip before starting to return results (for pagination)
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListSiteClientsParams defines parameters for ListSiteClients.
type ListSiteClientsParams struct {
	// Offset Number of items to skip before starting to return results (for pagination)
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListSiteDevicesParams defines parameters for ListSiteDevices.
type ListSiteDevicesParams struct {
	// Offset Number of items to skip before starting to return results (for pagination)
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListSites request
	ListSites(ctx context.Context, params *ListSitesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSiteClients request
	ListSiteClients(ctx context.Context, siteId SiteId, params *ListSiteClientsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetClientById request
	GetClientById(ctx context.Context, siteId SiteId, clientId ClientId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSiteDevices request
	ListSiteDevices(ctx context.Context, siteId SiteId, params *ListSiteDevicesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDeviceById request
	GetDeviceById(ctx context.Context, siteId SiteId, deviceId DeviceId, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListSites(ctx context.Context, params *ListSitesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSitesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSiteClients(ctx context.Context, siteId SiteId, params *ListSiteClientsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSiteClientsRequest(c.Server, siteId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetClientById(ctx context.Context, siteId SiteId, clientId ClientId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClientByIdRequest(c.Server, siteId, clientId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSiteDevices(ctx context.Context, siteId SiteId, params *ListSiteDevicesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSiteDevicesRequest(c.Server, siteId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDeviceById(ctx context.Context, siteId SiteId, deviceId DeviceId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeviceByIdRequest(c.Server, siteId, deviceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListSitesRequest generates requests for ListSites
func NewListSitesRequest(server string, params *ListSitesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sites")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSiteClientsRequest generates requests for ListSiteClients
func NewListSiteClientsRequest(server string, siteId SiteId, params *ListSiteClientsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "siteId", runtime.ParamLocationPath, siteId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sites/%s/clients", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetClientByIdRequest generates requests for GetClientById
func NewGetClientByIdRequest(server string, siteId SiteId, clientId ClientId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "siteId", runtime.ParamLocationPath, siteId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clientId", runtime.ParamLocationPath, clientId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sites/%s/clients/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSiteDevicesRequest generates requests for ListSiteDevices
func NewListSiteDevicesRequest(server string, siteId SiteId, params *ListSiteDevicesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "siteId", runtime.ParamLocationPath, siteId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sites/%s/devices", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDeviceByIdRequest generates requests for GetDeviceById
func NewGetDeviceByIdRequest(server string, siteId SiteId, deviceId DeviceId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "siteId", runtime.ParamLocationPath, siteId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "deviceId", runtime.ParamLocationPath, deviceId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sites/%s/devices/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListSitesWithResponse request
	ListSitesWithResponse(ctx context.Context, params *ListSitesParams, reqEditors ...RequestEditorFn) (*ListSitesResponse, error)

	// ListSiteClientsWithResponse request
	ListSiteClientsWithResponse(ctx context.Context, siteId SiteId, params *ListSiteClientsParams, reqEditors ...RequestEditorFn) (*ListSiteClientsResponse, error)

	// GetClientByIdWithResponse request
	GetClientByIdWithResponse(ctx context.Context, siteId SiteId, clientId ClientId, reqEditors ...RequestEditorFn) (*GetClientByIdResponse, error)

	// ListSiteDevicesWithResponse request
	ListSiteDevicesWithResponse(ctx context.Context, siteId SiteId, params *ListSiteDevicesParams, reqEditors ...RequestEditorFn) (*ListSiteDevicesResponse, error)

	// GetDeviceByIdWithResponse request
	GetDeviceByIdWithResponse(ctx context.Context, siteId SiteId, deviceId DeviceId, reqEditors ...RequestEditorFn) (*GetDeviceByIdResponse, error)
}

type ListSitesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SitesResponse
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r ListSitesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSitesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSiteClientsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ClientsResponse
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r ListSiteClientsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSiteClientsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetClientByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NetworkClient
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetClientByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClientByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSiteDevicesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DevicesResponse
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r ListSiteDevicesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSiteDevicesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDeviceByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Device
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetDeviceByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeviceByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListSitesWithResponse request returning *ListSitesResponse
func (c *ClientWithResponses) ListSitesWithResponse(ctx context.Context, params *ListSitesParams, reqEditors ...RequestEditorFn) (*ListSitesResponse, error) {
	rsp, err := c.ListSites(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSitesResponse(rsp)
}

// ListSiteClientsWithResponse request returning *ListSiteClientsResponse
func (c *ClientWithResponses) ListSiteClientsWithResponse(ctx context.Context, siteId SiteId, params *ListSiteClientsParams, reqEditors ...RequestEditorFn) (*ListSiteClientsResponse, error) {
	rsp, err := c.ListSiteClients(ctx, siteId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSiteClientsResponse(rsp)
}

// GetClientByIdWithResponse request returning *GetClientByIdResponse
func (c *ClientWithResponses) GetClientByIdWithResponse(ctx context.Context, siteId SiteId, clientId ClientId, reqEditors ...RequestEditorFn) (*GetClientByIdResponse, error) {
	rsp, err := c.GetClientById(ctx, siteId, clientId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClientByIdResponse(rsp)
}

// ListSiteDevicesWithResponse request returning *ListSiteDevicesResponse
func (c *ClientWithResponses) ListSiteDevicesWithResponse(ctx context.Context, siteId SiteId, params *ListSiteDevicesParams, reqEditors ...RequestEditorFn) (*ListSiteDevicesResponse, error) {
	rsp, err := c.ListSiteDevices(ctx, siteId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSiteDevicesResponse(rsp)
}

// GetDeviceByIdWithResponse request returning *GetDeviceByIdResponse
func (c *ClientWithResponses) GetDeviceByIdWithResponse(ctx context.Context, siteId SiteId, deviceId DeviceId, reqEditors ...RequestEditorFn) (*GetDeviceByIdResponse, error) {
	rsp, err := c.GetDeviceById(ctx, siteId, deviceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeviceByIdResponse(rsp)
}

// ParseListSitesResponse parses an HTTP response from a ListSitesWithResponse call
func ParseListSitesResponse(rsp *http.Response) (*ListSitesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSitesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SitesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListSiteClientsResponse parses an HTTP response from a ListSiteClientsWithResponse call
func ParseListSiteClientsResponse(rsp *http.Response) (*ListSiteClientsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSiteClientsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ClientsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetClientByIdResponse parses an HTTP response from a GetClientByIdWithResponse call
func ParseGetClientByIdResponse(rsp *http.Response) (*GetClientByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetClientByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NetworkClient
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListSiteDevicesResponse parses an HTTP response from a ListSiteDevicesWithResponse call
func ParseListSiteDevicesResponse(rsp *http.Response) (*ListSiteDevicesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSiteDevicesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DevicesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetDeviceByIdResponse parses an HTTP response from a GetDeviceByIdWithResponse call
func ParseGetDeviceByIdResponse(rsp *http.Response) (*GetDeviceByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeviceByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Device
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xba2/bOJf+K4RmgW0B2ZZsJ431adNcWu+kiREnb3enLXZo6cjmW5nUkFQST5D/vuBF",
	"d9lx2nemBXY/VY0o8vDwOc+58PjRCdk6ZRSoFE7w6KSY4zVI4Pp/JwkBKqeReo5AhJykkjDqBM7NClBG",
	"yR8ZIBIBlSQmwBGLkVwBCvVn6NXt7fQUxYyvsXztuA484HWagBM48eQAe7AY96IonvRG8djvTcbDsOe/",
	"mYxwOPKicThxXIeolVIsV47rULxWX4a5RK7D4Y+McIicQPIMXEeEK1hjJapZ0gmcLCNqpNyk6lshOaFL",
	"5+nJdU7hjoTw4o1F+rMdG3vjh4vhwRj3Ft7hUW80iSe9iT866nnxIj6KwfdDHHZvLMol+r6NXZA1ke1d",
	"fcAPZJ2tEc3WC7MdImEtkGSIg8w4RSlwlOIlVLczPLCi/pEB35SyJnqRqmARxDhLpPlkbRZzAt/zXGdN",
	"qP1fIS+hEpbAtcBXcSygQ+LLtqTiK0nRAmLGAQmJuSR0WdkBB5ElUqBXMdNbIRSruWoH5HVviBkhOndU",
	"3YLXuYU5kS+HkiByF5COjuI3OD4Y9yZH8VFv5B3iHvbDN71wMhpP3gyHCz8+7AaSMNJ8D4ye1MciZVSA",
	"poFLJs9ZRvUWQ0YlUH1gOE0TEmolD/4p1JYfyx08OmsQQgEqcC4ZAhqljFCJ3p3doIHWHjdf3vkDJbIY",
	"EHqHExL1SC48CDlTWwucPT4QEstMnLAInGDsjfM/XBqlXF7d/M/51e3lqdotWYOQeJ06gTP0hgc93+/5",
	"/o1/GHhe4Hm/OU9VXf0bh9gJnF8GJU8OzFsxOOOc8WurKaO3BoiZRFpzqIeuQbCMh4AYL7URMRCIMong",
	"gQipVr6lOJMrxsmf8M36nhrFoOPZFH2FzX7qbOnQb+jw9vL49ub91fX0t7O/WY1VnaAeyrfHOFoTIRQL",
	"5Dt9Khat+K/jMARhvBtnKXBJDKwN7JtWa0YjpXfOEqQHuQ5QZf+fnNOz8+PbixvHda7P5jfX05MbrYy3",
	"F1cnv56dOl+qNlyObfN0aZyfzNsvxSi2+CeEGgtG/Asi5FTCur0BXGxsl3prSnhyFaIohBKi4w7avclP",
	"Fd2vgOaevPgEvbo+PxmNRpNO0jIw8Hr+5Mb3Am8SjPzfHLekmwhL6CnctFXiOqSDQW9b7Km4vQwxviWo",
	"eIb8XIekx1HErWLr8kxnCJt3CAtBlhQi5YC2COS/Gfb9w77v9f1J10JrHG5d6cPxSbFULaqqewkvwHEQ",
	"4gBHgXcQHHXux/iF5gKnRKQJ3iD1VlnSiglpnreuptwIxQJtXanboE4MeAijTWP6OL3W1qP+vTibz+vm",
	"k79tLZOlCaFft4dw09NGvCZXRORQJqKCZsm+JXp7PgprWbeGtz2KugVW8VaDRGufbm7v26lCFCyq2CFJ",
	"rmIn+LSbHWYmUIKoJGC3yTMRlprEdSS2H90UpFXAwsGcY8PQDem/FAF5m+JCRmOyzIyv6jrsk4xzS1Hl",
	"wApj1A44HPrDBfgj7+DoAGAy6kJXDFhm3BJsFBE1H05mHZ6jov66TOdmip5IISQxCRvCYRqhEKd4QRKi",
	"Z3Srbtwc8kyFB07wqPzZPZHhSkkXPHZoz3Viwtf3mMNtqg5qkXTY4McVyJWiTzsUZWosKGvAd5gk+quK",
	"GDFOBBRLLRhLANPqWv8ALogJQbrPo1jpzo6snsO4P+pPvt8JGPP+C0zY1fE9j3EIz+Ld2mc5fm8XUiOp",
	"uiP13/TfHPX9I+VA/H+B7+hYYzIOhjg4jIMQguFhcDDsXIZFkHQ4D8Or+u02W7s9vX7zre5oq9AX8HDO",
	"gfy7QCvWHUaknN0RBbi94hvrIO6xQJUP94ly/J43uhn6wdgPvPH+UY6KqGG71SiSwYZxkBlaesury4vp",
	"5ZnjOlfn5/bpdvbu+vh0evnOcZ3Z9dU/pvPp1aX6b82RFh+2pcnSlHEJ0XbG0L7TqokoPMUkJDhJNqj8",
	"uLKYSTWbvNFwiVVfaBBWFaXhBavuMVdJk4W6OLAJBbflSypcXzP4Lv/asvJ2wQLkPeNfUTlRSa1IxT5V",
	"RNednNp4x4yz1UaQECdInwQFicxAdz9HPGNctt2v63AcEdax3EfCIVGcoQdU9rHvgtfqu30cfq7O7ZlN",
	"1QnXpVTfKILIR5QwRItNFa1VVH6qOFG35mG/VPaWG9q2sa7DWSbN35dYwj3eVLDSDINLhf+kTq1BjJsU",
	"tLugO3Bc12mORguoLlU2hrjOPab76ez/PeiP8qA/k4vaw3E87yxeSPI/QxLV4Mc9k6h6Ia1FqkWBsHm0",
	"77M1pj0OONLOCtQ0KB9dPaZvKOS24FUrRXaVzO0AlGK5QnKFJQpxJlS2vrKy1WT6Fhmqhc6WMm5uZsgM",
	"QKEaUVlMF5abNwD1Mumu6SxyK/qslqVblFgWWJ+JYgvFIBaGykz3jGBr5dr9ItiGQVYUWVOD65TwKfdR",
	"P/wuC7RBlKkh7G9/zZqDMoa2TXYUFzK6x9UToSi05Jdfi1TV6XdBInnZPdy227f2xGzP+zLxlaRpPTb3",
	"uuaTTOLkpFsRN+pdS9bOaKD7cq8KleKOLb89NNqvSeAaluxCxoyddUTI7F5JdgccneUxcrvWYnDZirqB",
	"qk3sSH1m7EylPHacieGJ0EH48ymPNgcaYR51iX2G8rf1NMr60SNv2B/h2HHtk8yfFrLuN8uBL3XjVoaa",
	"+76dOa5zevXxUv0znR+/vWheaegRe9Z91QrqjQXQy9BSKM91iqKxOa58Z90g4bKzhkghlIzvSLGKMc0a",
	"9fV/jg8c15mfz2YXt3PzVNeJHdFRy3roUgqXiNAIHnK7euX3FlhA9PpZTlnjh3kKEH1YpGI7tZT5kFCD",
	"FXvpD2rM4nVyQcrg+aTyTINruxw5wCgsmSR4pyC+1y3IM9hV+9sB3mcR24oqHyrhYomWhsaru+4Cn0l/",
	"2+hbYUq7UoCP5Jwg+7bDRg67FGOHfySRXH14/2eHiux892qEVvn7P0slDT137LlHnusfelUtDTtPIdbe",
	"moabd10rXZk8gC5RMU6t9662Xn/sHriHtaX640qkESdMk5td3GrhyXXuE0znWwlUq+5ZBvV9bHnT9xfF",
	"07J4osWTTp/t40P5DbTJVv/1OUDVhG/osX2GxV86UTUncked5GWlBRUaf0uXyX6FBYqTa4iBAw07bHdq",
	"hyCejzGZqo7sCUW3VJuDuXVPgKPb64saVxQdOd+VEbdUcLpt1q7Us71Pu/a2k/sZcskagvbKJBUDQ5hx",
	"IjdzNYlZ9Dglv8LmOOvK22z/BVoCVawAEYo5W7cP9dUcpOIMgT5nnjcCdGLbLGYJppD/cVpmdOJ13uW0",
	"AhxphrR9Tv/VO55Ne7+e/Xd5dFhLaDpICI1Z3j+DQx0VwBqTRJHOfyTw0E9wOddxAl8FEDS/I5xEXwl1",
	"OnpQ1FbyIm9FQt17okvNEehbhCXH6zWWJESmeIgks4rIS2umLCNceyctXHMlWA1cRf8z/UxvVLyp5ifC",
	"TgYRSlio6+9yxVm2XGlYtxSNJfp9kHL2sBnYVZt58u96hV9+QepEFVWYzqLP9DhJ8hxcIGsCCNO8xwal",
	"WItxR7BeujgHZE4on/YtFoBUomdmzOsGAmEOKOUQkweI0D2Rq2ck/d0kucX+d+07X9zewIrPtIcU/tEa",
	"U7yEtYoelK4TIhQM1WtbiSP0DqhkfKPfrxklknE7xKSXSHIcflUOT43AtTYhNeoacKKz5jzdVxBUxKm1",
	"qhOfECwVWNy9nZ/2Rr2TBGc6pcy4gudKylQEgwFLgZqWsT7jy4H9WgxqH+k6gTSRzi6EOq6TX8QGjt/3",
	"+p5OJlOgOCVO4Iz6Xn+kUiQsV9rabVNY8Ogsu9LNa5CcwB0IhPNeSzBqVUyLk8QejZ6lgHaeRUHzyM5w",
	"uDItkRxSDgI0UFDCljo6X3KWpUrzlfq0NSJjOsaO+lrNRYFyGtn7grntb6s2N29h4XLIwHamKvZ9ZqRp",
	"un360mibHHreHh18+/XI1Z1JR4/cPNOAjLOkKFIY48rPxJznk+uMPX/baoX4g1obov5o/PxHRZ+o9iDZ",
	"eo35Jr+yUZDI+wwlXqoTMB7S0f7Glu0eTffq08Ce6Hfgz/b75DB5pSTO1HG5KF0xquh3ym7y968/U1vj",
	"STaIccQhNM/VZiETQZimDpXWEAm7IGd7cl4MPNtPvAfwfiqINluQvgWk+bH/MJhaAXTIjPNoMcdrfqC7",
	"EDt4zH+i8LQHeCOQmCQ6Ai58BcILlkm1etE+VIWyiwgNkywidBlo51Rvr0Ov7lXIOri3t7mv1ZjcKdg7",
	"LWUO05mLPhyf6Ne3utGsuOWvuq0eavTDChvANZfOi7yiwyDegTSqe7vR1+5/lTkUP1f5S3Fer1G/BOXF",
	"OapD/zEgfweyKcae+LZE+R2M3PTcrzizhGxu3BUl27DKhIqvP1MsBAtNFUmr8GUMbC/0/q8wcPP+8lsY",
	"OD/mH8bAOTo6GTg/0F0IHTzmv6X61zFwHbpNCn6PeaR7HfPxJoWzmUQEOj04bzRE6re2DdMkDFWmrnRf",
	"vNJNFK5pyzF8ftW8gy/uOVReE+bkXLkHscbeTc5Gq38xORd9zH+DCbwI+dbt/WhWbojRiflKYUYfTrUk",
	"8+mLUqwAfpcfXaNxiqlMqpkwt7LOx/Ld0860XGWUmBO8SIpblnzO6s/nHH8y7PuHR32/rz7Z3spT/wnC",
	"hmW8LezTk9qjVUxzgzvy/LJpRZRFn7lNiLY18tkDacxYVgbKmU4LzmyV46uR264CQjlZ7oSfvjz9bwAA",
	"AP//mfSZ1J07AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
