// Package network provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package network

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ClientAccessType.
const (
	BLOCKED    ClientAccessType = "BLOCKED"
	DEFAULT    ClientAccessType = "DEFAULT"
	RESTRICTED ClientAccessType = "RESTRICTED"
)

// Defines values for ClientListItemType.
const (
	WIRED    ClientListItemType = "WIRED"
	WIRELESS ClientListItemType = "WIRELESS"
)

// Defines values for DeviceState.
const (
	DeviceStateOFFLINE      DeviceState = "OFFLINE"
	DeviceStateONLINE       DeviceState = "ONLINE"
	DeviceStatePROVISIONING DeviceState = "PROVISIONING"
	DeviceStateUPGRADING    DeviceState = "UPGRADING"
)

// Defines values for DeviceListItemFeatures.
const (
	AccessPoint DeviceListItemFeatures = "accessPoint"
	Gateway     DeviceListItemFeatures = "gateway"
	Routing     DeviceListItemFeatures = "routing"
	Switching   DeviceListItemFeatures = "switching"
)

// Defines values for DeviceListItemInterfaces.
const (
	Ports  DeviceListItemInterfaces = "ports"
	Radios DeviceListItemInterfaces = "radios"
	Wan    DeviceListItemInterfaces = "wan"
)

// Defines values for DeviceListItemState.
const (
	DeviceListItemStateOFFLINE      DeviceListItemState = "OFFLINE"
	DeviceListItemStateONLINE       DeviceListItemState = "ONLINE"
	DeviceListItemStatePROVISIONING DeviceListItemState = "PROVISIONING"
	DeviceListItemStateUPGRADING    DeviceListItemState = "UPGRADING"
)

// Defines values for PoEStandard.
const (
	N8023af PoEStandard = "802.3af"
	N8023at PoEStandard = "802.3at"
	N8023bt PoEStandard = "802.3bt"
)

// Defines values for PoEState.
const (
	PoEStateDISABLED PoEState = "DISABLED"
	PoEStateDOWN     PoEState = "DOWN"
	PoEStateUP       PoEState = "UP"
)

// Defines values for PortConnector.
const (
	RJ45    PortConnector = "RJ45"
	SFP     PortConnector = "SFP"
	SFPPLUS PortConnector = "SFPPLUS"
)

// Defines values for PortState.
const (
	PortStateDOWN PortState = "DOWN"
	PortStateUP   PortState = "UP"
)

// Defines values for RadioChannelWidthMHz.
const (
	N160 RadioChannelWidthMHz = 160
	N20  RadioChannelWidthMHz = 20
	N40  RadioChannelWidthMHz = 40
	N80  RadioChannelWidthMHz = 80
)

// Defines values for RadioFrequencyGHz.
const (
	N24 RadioFrequencyGHz = 2.4
	N5  RadioFrequencyGHz = 5
	N6  RadioFrequencyGHz = 6
)

// Defines values for RadioWlanStandard.
const (
	N80211a  RadioWlanStandard = "802.11a"
	N80211ac RadioWlanStandard = "802.11ac"
	N80211ax RadioWlanStandard = "802.11ax"
	N80211b  RadioWlanStandard = "802.11b"
	N80211be RadioWlanStandard = "802.11be"
	N80211g  RadioWlanStandard = "802.11g"
	N80211n  RadioWlanStandard = "802.11n"
)

// ClientAccess defines model for ClientAccess.
type ClientAccess struct {
	// Type Access control type
	Type ClientAccessType `json:"type"`
}

// ClientAccessType Access control type
type ClientAccessType string

// ClientListItem defines model for ClientListItem.
type ClientListItem struct {
	Access ClientAccess `json:"access"`

	// ConnectedAt Timestamp when client connected (RFC3339 format)
	ConnectedAt time.Time `json:"connectedAt"`

	// Id Unique identifier for the client
	Id openapi_types.UUID `json:"id"`

	// IpAddress IP address assigned to the client
	IpAddress string `json:"ipAddress"`

	// MacAddress MAC address of the client
	MacAddress string `json:"macAddress"`

	// Name Display name or hostname of the client
	Name string `json:"name"`

	// Type Connection type
	Type ClientListItemType `json:"type"`

	// UplinkDeviceId ID of the device this client is connected to
	UplinkDeviceId openapi_types.UUID `json:"uplinkDeviceId"`
}

// ClientListItemType Connection type
type ClientListItemType string

// ClientsResponse defines model for ClientsResponse.
type ClientsResponse struct {
	// Count Number of items in current response
	Count int              `json:"count"`
	Data  []ClientListItem `json:"data"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// TotalCount Total number of items available
	TotalCount int `json:"totalCount"`
}

// Device defines model for Device.
type Device struct {
	// ConfigurationId Current configuration identifier
	ConfigurationId string `json:"configurationId"`

	// Features Feature-specific configuration and capabilities
	Features map[string]map[string]interface{} `json:"features"`

	// FirmwareUpdatable Whether firmware update is available
	FirmwareUpdatable bool `json:"firmwareUpdatable"`

	// FirmwareVersion Current firmware version
	FirmwareVersion string `json:"firmwareVersion"`

	// Id Unique identifier for the device
	Id openapi_types.UUID `json:"id"`

	// Interfaces Network interfaces available on the device
	Interfaces DeviceInterfaces `json:"interfaces"`

	// IpAddress IP address of the device
	IpAddress string `json:"ipAddress"`

	// MacAddress MAC address of the device
	MacAddress string `json:"macAddress"`

	// Model Device model identifier
	Model string `json:"model"`

	// Name Display name of the device
	Name string `json:"name"`

	// ProvisionedAt Timestamp when device was provisioned (RFC3339 format)
	ProvisionedAt time.Time `json:"provisionedAt"`

	// State Current operational state
	State DeviceState `json:"state"`

	// Supported Whether this device is officially supported
	Supported bool `json:"supported"`
}

// DeviceState Current operational state
type DeviceState string

// DeviceInterfaces Network interfaces available on the device
type DeviceInterfaces struct {
	// Ports Physical ethernet ports
	Ports *[]Port `json:"ports,omitempty"`

	// Radios Wireless radio interfaces
	Radios *[]Radio `json:"radios,omitempty"`
}

// DeviceListItem defines model for DeviceListItem.
type DeviceListItem struct {
	// Features List of features supported by this device
	Features []DeviceListItemFeatures `json:"features"`

	// Id Unique identifier for the device
	Id openapi_types.UUID `json:"id"`

	// Interfaces Types of network interfaces available
	Interfaces []DeviceListItemInterfaces `json:"interfaces"`

	// IpAddress IP address of the device
	IpAddress string `json:"ipAddress"`

	// MacAddress MAC address of the device
	MacAddress string `json:"macAddress"`

	// Model Device model identifier
	Model string `json:"model"`

	// Name Display name of the device
	Name string `json:"name"`

	// State Current operational state
	State DeviceListItemState `json:"state"`
}

// DeviceListItemFeatures defines model for DeviceListItem.Features.
type DeviceListItemFeatures string

// DeviceListItemInterfaces defines model for DeviceListItem.Interfaces.
type DeviceListItemInterfaces string

// DeviceListItemState Current operational state
type DeviceListItemState string

// DevicesResponse defines model for DevicesResponse.
type DevicesResponse struct {
	// Count Number of items in current response
	Count int              `json:"count"`
	Data  []DeviceListItem `json:"data"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// TotalCount Total number of items available
	TotalCount int `json:"totalCount"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Human-readable error message
	Message string `json:"message"`

	// RequestPath The request path that caused the error
	RequestPath string `json:"requestPath"`

	// StatusCode HTTP status code
	StatusCode int `json:"statusCode"`

	// StatusName HTTP status name
	StatusName string `json:"statusName"`

	// Timestamp Timestamp when the error occurred (RFC3339 format)
	Timestamp time.Time `json:"timestamp"`
}

// NetworkClient defines model for NetworkClient.
type NetworkClient = ClientListItem

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	// Count Number of items in current response
	Count int `json:"count"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// TotalCount Total number of items available
	TotalCount int `json:"totalCount"`
}

// PoE Power over Ethernet configuration and status
type PoE struct {
	// Enabled Whether PoE is enabled on this port
	Enabled bool `json:"enabled"`

	// Standard PoE standard supported
	Standard PoEStandard `json:"standard"`

	// State Current PoE state
	State PoEState `json:"state"`

	// Type PoE type number
	Type int `json:"type"`
}

// PoEStandard PoE standard supported
type PoEStandard string

// PoEState Current PoE state
type PoEState string

// Port defines model for Port.
type Port struct {
	// Connector Physical connector type
	Connector PortConnector `json:"connector"`

	// Idx Port index number (1-based)
	Idx int `json:"idx"`

	// MaxSpeedMbps Maximum supported speed in Mbps
	MaxSpeedMbps int `json:"maxSpeedMbps"`

	// Poe Power over Ethernet configuration and status
	Poe *PoE `json:"poe,omitempty"`

	// SpeedMbps Current negotiated speed in Mbps
	SpeedMbps int `json:"speedMbps"`

	// State Current port state
	State PortState `json:"state"`
}

// PortConnector Physical connector type
type PortConnector string

// PortState Current port state
type PortState string

// Radio defines model for Radio.
type Radio struct {
	// Channel WiFi channel number
	Channel int `json:"channel"`

	// ChannelWidthMHz Channel width in MHz
	ChannelWidthMHz RadioChannelWidthMHz `json:"channelWidthMHz"`

	// FrequencyGHz Operating frequency in GHz
	FrequencyGHz RadioFrequencyGHz `json:"frequencyGHz"`

	// WlanStandard WiFi standard supported
	WlanStandard RadioWlanStandard `json:"wlanStandard"`
}

// RadioChannelWidthMHz Channel width in MHz
type RadioChannelWidthMHz int

// RadioFrequencyGHz Operating frequency in GHz
type RadioFrequencyGHz float32

// RadioWlanStandard WiFi standard supported
type RadioWlanStandard string

// SiteListItem defines model for SiteListItem.
type SiteListItem struct {
	// Id Unique identifier for the site
	Id openapi_types.UUID `json:"id"`

	// InternalReference Internal reference name used in UniFi controller URLs
	InternalReference string `json:"internalReference"`

	// Name Display name of the site
	Name string `json:"name"`
}

// SitesResponse defines model for SitesResponse.
type SitesResponse struct {
	// Count Number of items in current response
	Count int            `json:"count"`
	Data  []SiteListItem `json:"data"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// TotalCount Total number of items available
	TotalCount int `json:"totalCount"`
}

// ClientId defines model for ClientId.
type ClientId = openapi_types.UUID

// DeviceId defines model for DeviceId.
type DeviceId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// SiteId defines model for SiteId.
type SiteId = openapi_types.UUID

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListSitesParams defines parameters for ListSites.
type ListSitesParams struct {
	// Offset Number of items to skip before starting to return results (for pagination)
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListSiteClientsParams defines parameters for ListSiteClients.
type ListSiteClientsParams struct {
	// Offset Number of items to skip before starting to return results (for pagination)
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListSiteDevicesParams defines parameters for ListSiteDevices.
type ListSiteDevicesParams struct {
	// Offset Number of items to skip before starting to return results (for pagination)
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListSites request
	ListSites(ctx context.Context, params *ListSitesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSiteClients request
	ListSiteClients(ctx context.Context, siteId SiteId, params *ListSiteClientsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetClientById request
	GetClientById(ctx context.Context, siteId SiteId, clientId ClientId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSiteDevices request
	ListSiteDevices(ctx context.Context, siteId SiteId, params *ListSiteDevicesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDeviceById request
	GetDeviceById(ctx context.Context, siteId SiteId, deviceId DeviceId, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListSites(ctx context.Context, params *ListSitesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSitesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSiteClients(ctx context.Context, siteId SiteId, params *ListSiteClientsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSiteClientsRequest(c.Server, siteId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetClientById(ctx context.Context, siteId SiteId, clientId ClientId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClientByIdRequest(c.Server, siteId, clientId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSiteDevices(ctx context.Context, siteId SiteId, params *ListSiteDevicesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSiteDevicesRequest(c.Server, siteId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDeviceById(ctx context.Context, siteId SiteId, deviceId DeviceId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeviceByIdRequest(c.Server, siteId, deviceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListSitesRequest generates requests for ListSites
func NewListSitesRequest(server string, params *ListSitesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sites")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSiteClientsRequest generates requests for ListSiteClients
func NewListSiteClientsRequest(server string, siteId SiteId, params *ListSiteClientsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "siteId", runtime.ParamLocationPath, siteId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sites/%s/clients", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetClientByIdRequest generates requests for GetClientById
func NewGetClientByIdRequest(server string, siteId SiteId, clientId ClientId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "siteId", runtime.ParamLocationPath, siteId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clientId", runtime.ParamLocationPath, clientId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sites/%s/clients/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSiteDevicesRequest generates requests for ListSiteDevices
func NewListSiteDevicesRequest(server string, siteId SiteId, params *ListSiteDevicesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "siteId", runtime.ParamLocationPath, siteId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sites/%s/devices", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDeviceByIdRequest generates requests for GetDeviceById
func NewGetDeviceByIdRequest(server string, siteId SiteId, deviceId DeviceId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "siteId", runtime.ParamLocationPath, siteId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "deviceId", runtime.ParamLocationPath, deviceId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sites/%s/devices/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListSitesWithResponse request
	ListSitesWithResponse(ctx context.Context, params *ListSitesParams, reqEditors ...RequestEditorFn) (*ListSitesResponse, error)

	// ListSiteClientsWithResponse request
	ListSiteClientsWithResponse(ctx context.Context, siteId SiteId, params *ListSiteClientsParams, reqEditors ...RequestEditorFn) (*ListSiteClientsResponse, error)

	// GetClientByIdWithResponse request
	GetClientByIdWithResponse(ctx context.Context, siteId SiteId, clientId ClientId, reqEditors ...RequestEditorFn) (*GetClientByIdResponse, error)

	// ListSiteDevicesWithResponse request
	ListSiteDevicesWithResponse(ctx context.Context, siteId SiteId, params *ListSiteDevicesParams, reqEditors ...RequestEditorFn) (*ListSiteDevicesResponse, error)

	// GetDeviceByIdWithResponse request
	GetDeviceByIdWithResponse(ctx context.Context, siteId SiteId, deviceId DeviceId, reqEditors ...RequestEditorFn) (*GetDeviceByIdResponse, error)
}

type ListSitesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SitesResponse
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r ListSitesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSitesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSiteClientsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ClientsResponse
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r ListSiteClientsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSiteClientsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetClientByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NetworkClient
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetClientByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClientByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSiteDevicesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DevicesResponse
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r ListSiteDevicesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSiteDevicesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDeviceByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Device
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetDeviceByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeviceByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListSitesWithResponse request returning *ListSitesResponse
func (c *ClientWithResponses) ListSitesWithResponse(ctx context.Context, params *ListSitesParams, reqEditors ...RequestEditorFn) (*ListSitesResponse, error) {
	rsp, err := c.ListSites(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSitesResponse(rsp)
}

// ListSiteClientsWithResponse request returning *ListSiteClientsResponse
func (c *ClientWithResponses) ListSiteClientsWithResponse(ctx context.Context, siteId SiteId, params *ListSiteClientsParams, reqEditors ...RequestEditorFn) (*ListSiteClientsResponse, error) {
	rsp, err := c.ListSiteClients(ctx, siteId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSiteClientsResponse(rsp)
}

// GetClientByIdWithResponse request returning *GetClientByIdResponse
func (c *ClientWithResponses) GetClientByIdWithResponse(ctx context.Context, siteId SiteId, clientId ClientId, reqEditors ...RequestEditorFn) (*GetClientByIdResponse, error) {
	rsp, err := c.GetClientById(ctx, siteId, clientId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClientByIdResponse(rsp)
}

// ListSiteDevicesWithResponse request returning *ListSiteDevicesResponse
func (c *ClientWithResponses) ListSiteDevicesWithResponse(ctx context.Context, siteId SiteId, params *ListSiteDevicesParams, reqEditors ...RequestEditorFn) (*ListSiteDevicesResponse, error) {
	rsp, err := c.ListSiteDevices(ctx, siteId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSiteDevicesResponse(rsp)
}

// GetDeviceByIdWithResponse request returning *GetDeviceByIdResponse
func (c *ClientWithResponses) GetDeviceByIdWithResponse(ctx context.Context, siteId SiteId, deviceId DeviceId, reqEditors ...RequestEditorFn) (*GetDeviceByIdResponse, error) {
	rsp, err := c.GetDeviceById(ctx, siteId, deviceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeviceByIdResponse(rsp)
}

// ParseListSitesResponse parses an HTTP response from a ListSitesWithResponse call
func ParseListSitesResponse(rsp *http.Response) (*ListSitesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSitesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SitesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListSiteClientsResponse parses an HTTP response from a ListSiteClientsWithResponse call
func ParseListSiteClientsResponse(rsp *http.Response) (*ListSiteClientsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSiteClientsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ClientsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetClientByIdResponse parses an HTTP response from a GetClientByIdWithResponse call
func ParseGetClientByIdResponse(rsp *http.Response) (*GetClientByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetClientByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NetworkClient
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListSiteDevicesResponse parses an HTTP response from a ListSiteDevicesWithResponse call
func ParseListSiteDevicesResponse(rsp *http.Response) (*ListSiteDevicesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSiteDevicesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DevicesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetDeviceByIdResponse parses an HTTP response from a GetDeviceByIdWithResponse call
func ParseGetDeviceByIdResponse(rsp *http.Response) (*GetDeviceByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeviceByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Device
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xba2/bOJf+K4RmgW0B2ZZs52J92jSX1jtpYsTJ291pix1aOrL5ViY1JJXEE+S/L3jR",
	"XU6c9J1pgd1PVSNSPDx8znMuPH5wQrZOGQUqhRM8OCnmeA0SuP7fcUKAymmkniMQISepJIw6gXO9ApRR",
	"8kcGiERAJYkJcMRiJFeAQj0Nvbm5mZ6gmPE1lm8d14F7vE4TcAInnuxhDxbjXhTFk94oHvu9yXgY9vyD",
	"yQiHIy8ahxPHdYhaKcVy5bgOxWs1M8wlch0Of2SEQ+QEkmfgOiJcwRorUc2STuBkGVEj5SZVc4XkhC6d",
	"x0fXOYFbEsKLNxbpaU9s7MAPF8O9Me4tvP3D3mgST3oTf3TY8+JFfBiD74c47N5YlEv0fRs7J2si27v6",
	"iO/JOlsjmq0XZjtEwlogyRAHmXGKUuAoxUuobme4Z0X9IwO+KWVN9CJVwSKIcZZIM2VtFnMC3/NcZ02o",
	"/V8hL6ESlsC1wJdxLKBD4ou2pOIbSdECYsYBCYm5JHRZ2QEHkSVSoDcx01shFKtv1Q7I694QM0J07qi6",
	"Ba9zC3MiXw4lQeRTQDo8jA9wvDfuTQ7jw97I28c97IcHvXAyGk8OhsOFH+93A0kYab4HRo9qskgZFaBp",
	"4ILJM5ZRvcWQUQlUHxhO04SEWsmDfwq15YdyBw/OGoRQgAqcC4aARikjVKL3p9dooLXHzcxbf6BEFgNC",
	"b3FCoh7JhQchZ2prgbPDBCGxzMQxi8AJxt44/8OFUcrF5fX/nF3eXJyo3ZI1CInXqRM4Q2+41/P9nu9f",
	"+/uB5wWe95vzWNXVv3GIncD5ZVDy5MC8FYNTzhm/spoyemuAmEmkNYd66AoEy3gIiPFSGxEDgSiTCO6J",
	"kGrlG4ozuWKc/Amv1vfUKAYdzaboG2x2U2dLh35DhzcXRzfXHy6vpr+d/s1qrOoE9VC+PcbRmgihWCDf",
	"6WOxaMV/HYUhCOPdOEuBS2JgbWDftFozGim9c5YgPch1gCr7/+ycnJ4d3ZxfO65zdTq/vpoeX2tlvDu/",
	"PP719MT5WrXhcmybp0vj/Gzefi1GscU/IdRYMOKfEyGnEtbtDeBiY0+pt6aER1chikIoITrqoN3r/FTR",
	"3Qpo7smLKejN1dnxaDSadJKWgYHX8yfXvhd4k2Dk/+a4Jd1EWEJP4aatEtchHQx602JPxe1liPGaoOIZ",
	"8nMdkh5FEbeKrcsznSFs3iEsBFlSiJQD2iKQfzDs+/t93+v7k66F1jjcutLHo+NiqVpUVfcSXoDjIMQB",
	"jgJvLzjs3I/xC80FTohIE7xB6q2ypBUT0jxvXU25EYoF2rpSt0EdG/AQRpvG9Gl6pa1H/Xt+Op/XzSd/",
	"21omSxNCv20P4aYnjXhNrojIoUxEBc2SvSZ6ez4Ka1m3hrc9iroFVvFWg0Rrn25u79upQhQsqtghSS5j",
	"J/j8NDvMTKAEUUnAbpNnIiw1ietIbDe6KUirgIWDOceGoRvSfy0C8jbFhYzGZJkZX9V12McZ55aiyoEV",
	"xqgdcDj0hwvwR97e4R7AZNSFrhiwzLgl2Cgi6ns4mXV4jor66zKdmU/0RAohiUnYEA7TCIU4xQuSEP1F",
	"t+rGzSHPVHjgBA/Kn90RGa6UdMFDh/ZcJyZ8fYc53KTqoBZJhw1+WoFcKfq0Q1GmxoKyBnyLSaJnVcSI",
	"cSKgWGrBWAKYVtf6B3BBTAjSfR7FSrd2ZPUcxv1Rf/L9TsCY919gwq6O73mMQ3gW79Y+y/E7u5AaSdUd",
	"qX/QPzjs+4fKgfj/At/RscZkHAxxsB8HIQTD/WBv2LkMiyDpcB6GV/XbbbZ2c3J18Fp3tFXoc7g/40D+",
	"XaAV6w4jUs5uiQLcTvGNdRB3WKDKxF2iHL/nja6HfjD2A2+8e5SjImrYbjWKZLBhHGSGlt7y8uJ8enHq",
	"uM7l2Zl9upm9vzo6mV68d1xndnX5j+l8enmh/ltzpMXEtjRZmjIuIdrOGNp3WjURhaeYhAQnyQaVkyuL",
	"mVSzyRsNl1j1hQZhVVEaXrDqHnOVNFmoiwObUHBbvqTC9TWD7/KvLStvFyxA3jH+DZUfKqkVqdiniui6",
	"k1Mb7/jibLURJMQJ0idBQSIz0N3NEc8Yl2336zocR4R1LPeJcEgUZ+gBlX3suuCVmreLw8/VuT2zqTrh",
	"upRqjiKIfEQJQ7TYVNFaReXnihN1ax72a2VvuaFtG+s6nGXS/H2JJdzhTQUrzTC4VPhP6tQaxLhJQbsL",
	"+gSO6zrN0WgB1aXKxhDXucN0N539vwf9UR70Z3JROziO553FC0n+Z0iiGvy4YxJVL6S1SLUoEDaP9kO2",
	"xrTHAUfaWYH6DMpHV4/pFYXcFrxqpciukrkdgFIsV0iusEQhzoTK1ldWtppMr5GhWuhsKeP6eobMABSq",
	"EZXFdGG5eQNQL5M+9TmL3Io+q2XpFiWWBdZnothCMYiFoTLTHSPYWrl2twi2YZAVRdbU4DolfMp91A+/",
	"ywJtEGVqCLvbX7PmoIyhbZMdxYWM7nD1RCgKLfnl1yJVdfpdkEhedg+37fat/WG2432Z+EbStB6be13f",
	"k0zi5LhbEdfqXUvWzmig+3KvCpXiji2/PTTar0ngGpbsQsaMnXZEyOxOSXYLHJ3mMXK71mJw2Yq6gapN",
	"PJH6zNipSnnsOBPDE6GD8OdTHm0ONMI86hL7FOVv62mU9aOH3rA/wrHj2ieZPy1k3W+WA1/qxq0MNfd9",
	"M3Nc5+Ty04X6Zzo/enfevNLQI3as+6oV1BsLoJehpVCe6xRFY3Nc+c66QcJlZw2RQigZfyLFKsY0a9RX",
	"/znec1xnfjabnd/MzVNdJ3ZERy3rvkspXCJCI7jP7eqN31tgAdHbZzllje/nKUD0cZGK7dRS5kNCDVbs",
	"pSfUmMXr5IKUwfNJ5akG13Y5coBRWDJJ8JOC+F63IM9gV+3vCfA+i9hWVHlfCRdLtDQ0Xt11F/hM+ttG",
	"3wpT2pUCfCJnBNm3HTay36UYO/wTieTq44c/O1Rkv3enRmiVf/izVNLQc8eee+i5/r5X1dKw8xRi7a1p",
	"uHnftdKlyQPoEhXj1Hrva+v1x+6eu19bqj+uRBpxwjS52cWtFh5d5y7BdL6VQLXqnmVQ38eWN31/UTwt",
	"iydaPOn02T7el3OgTbb6r88BqiZ8Q4/tMyz+0omqOZFP1EleVlpQofFrukx2KyxQnFxBDBxo2GG7UzsE",
	"8XyMyVR1ZE8ouqHaHMytewIc3Vyd17ii6Mj5roy4pYKTbV/tSj3b+7Rrbzu5nyGXrCFop0xSMTCEGSdy",
	"M1cfMYsepeRX2BxlXXmb7b9AS6CKFSBCMWfr9qG+mYNUnCHQl8zzRoCObZvFLMEU8j9Oy4xOvM27nFaA",
	"I82Qts/pv3pHs2nv19P/Lo8OawlNBwmhMcv7Z3CoowJYY5Io0vmPBO77CS6/dZTANwEEzW8JJ9E3Qp2O",
	"HhS1lbzIq/ary8sR6JuDJcfrNZYkRKZgiCSzm8/LaaYUI1x7Dy1ccw1YDVbFF8ozShWlMooSpuKSpgZF",
	"/wv9Qq9VHEqERvS5HndU9gYp4Vwrh86aOcuWKz22dR5Yot8HKWf3m4EVtJlO/64X/OUXpA5eMYpZ5As9",
	"SpI8VRfIWgrCNG/FQSnWy98SrJcujguZg8w/+w4LQCofNF/MywsCYQ4o5RCTe4jQHZGrZyT93eTCO+07",
	"X9xe1IovtIeUmaA1pngJaxVkqONJiFBoVa9twY7QW6CS8Y1+v2aUSMbtEJOFIslx+E0dohqBa91EatQV",
	"4EQn13lVQCFV8avWqs6PQrCMYeH5bn7SG/WOE5zpzDPjCsUrKVMRDAYsBWo6y/qMLwd2thjUJulygjQB",
	"URPIjuvkd7SB4/e9vqfzzBQoTokTOKO+1x+p7AnLlSYC2y8WPDjLrkz0CiQncAsC4bwNE4wqFQnjJAe1",
	"/kphAXmCBc1jOsXhynRLckg5CNDgQAlb6sB9yVmWapOJm7ZmLMyYW1+rtqhdTiN7lTC3rW/VvuctBF0O",
	"GdimVUXMz4w0/biPXxsdlUPP26G5b7f2ubqf6Wifm2cahHGWFPULY1D5mZjzfHSdsedvW60Qf1DrUNST",
	"xs9PKlpItXPJ1mvMN/ltjoJE3oIo8VKdgHGejnZFtqL3YBpbHwf2RL8Df7YVKIfJGyVxpo7LRemKUcXS",
	"U3adv3/7hdryT7JBjCMOoXmu9hGZ4ML0e6iMh0h4CnK2XefFwLOtxjsA76eCaLM76TUgzY/9h8HUCqCj",
	"aZwHkjle8wN9CrGDh/zXC487gDcCiUmig+PCPyC8YJlUqxedRVUou4jQMMkiQpeBdkj1zjv05k5Fs4M7",
	"e9H7Vo3JHYG97lLmMJ256OPRsX59o3vQigaAqqvqoUarrLCxXXPpvP4rOgziPUijuncbfSP/V5lD8UuW",
	"vxTn9fL1S1BenKM69B8D8vcgm2LsiG9LlN/ByE3P/YYzS8jmMl5Rsg2lTHj49gvFQrDQFJi0Cl/GwPau",
	"7/8KAzevNl/DwPkx/zAGztHRycD5gT6F0MFD/jOrfx0D16HbpOAPmEe6DTIfbzI9mz1EoFOCs0avpH5r",
	"OzRNklBl6kpjxhvdX+Gajh3D55fN6/niCkTlMmFOzpUrEmvs3eRstPoXk3PR4vw3mMCLkG/d3o9m5YYY",
	"nZiv1Gz04VSrNZ+/KsUK4Lf50TV6qjpLDa1M86F89/hkKq4ySswJXiTFBUz+zeov6xx/Muz7+4d9v6+m",
	"bO/yqf86YcMy3hb28VHt0SqmucEncvuyn0WU9aC5TYi29fjZA2l8sawGlF86KTizVamvRm5PFQ3Kj+VO",
	"+PHr4/8GAAD//+II89K4OwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
